### ISSUE TITLE
WebAPI Basic Security - wiki updates required

### ISSUE THREAD

**Issue by ambuj369** [OHDSI/WebAPI#1099]
Hello Team,

I am implementing the basic security feature in Atlas by following the contents mentioned in following path - 

https://github.com/OHDSI/WebAPI/wiki/Basic-Security-Configuration
https://github.com/OHDSI/WebAPI/wiki/Atlas-Security

Whenever. I try to access WebAPI/source/sources , I get the following error on webpage :
![WebAPIError](https://user-images.githubusercontent.com/47858365/58020119-dc812100-7b24-11e9-9a08-adaa97e9a063.jpg)

As per my understanding, if we don't see the source/source_daimon details through above link, something is not correct. However, I moved ahead with Atlas and got the errors as shown below:

![AtlasERROR](https://user-images.githubusercontent.com/47858365/58020173-08040b80-7b25-11e9-8582-041d8e2c1ea0.png)

P.S: If I keep security.provider as DisabledSecurity and rest of the settings as per Basic Security, I am able to open WebAPI/source/sources page, but Atlas throws another error 403.

I believe similar issue is being faced by multiple users. Please look into this issue as there is not any workaround or so and update if anything is being missed or not implemented as per guidelines.

Thank you
- Ambuj

**Comment by anthonysena** [comment]
Hi @ambuj369 - thanks for posting this issue. It looks like you have security enabled since you are getting a 401 error. The reason that you cannot browse to `WebAPI/source/sources` is that your credentials will need to be passed when retrieving the protected end point. 

A few questions/requests based on your note:
- Can you share the settings.xml profile you used to compile WebAPI with security enabled? Please be sure to strip out any sensitive information before posting as a file to this issue.
- Can you confirm that the account used to access the credential database has rights to do so?
- Can you confirm that you can open the REST endpoint: `WebAPI/info` to confirm the version you are using? I also believe that particular endpoint is not protected by security so it will allow us to confirm the version of WebAPI you are using.
- On the ATLAS side, can you share your config-local.js to confirm those settings as well?

**Comment by ambuj369** [comment]
hello @anthonysena 
thank you for reverting.
I am attaching settings.xml and screenshots for config-local.js, Atlas homepage, WebAPI/source/sources and WebAPI/info

![Screenshot from 2019-05-21 20-56-08](https://user-images.githubusercontent.com/47858365/58109695-baae9980-7c0b-11e9-82db-aaa6031fbba5.png)
![Screenshot from 2019-05-21 20-57-46](https://user-images.githubusercontent.com/47858365/58109697-baae9980-7c0b-11e9-9827-5ea0cb3d67dc.png)
![Screenshot from 2019-05-21 20-58-16](https://user-images.githubusercontent.com/47858365/58109700-bb473000-7c0b-11e9-910c-7ee0d6385cc0.png)
![Screenshot from 2019-05-21 20-58-51](https://user-images.githubusercontent.com/47858365/58109701-bb473000-7c0b-11e9-854c-53c55a2dcae7.png)

**Comment by anthonysena** [comment]
Thanks for sharing these details @ambuj369. A few comments and more requests:

- Based on your `config-local.js`, I would expect your ATLAS display to only show the DB authentication provider versus the full list of supported authentication providers. I noticed in your screenshot the document was not saved so perhaps that is part of the issue there.
- On the settings.xml, I see you've modified the `<security.db.datasource.authenticationQuery>` from

`select password from ${security.db.datasource.schema}.demo_security where email = ?`
to
`select password from ${security.db.datasource.schema}.demo_security where lower(email) = lower(?)`

I wouldn't expect this to be an issue but just noting it as a difference. 

Can you share any errors you may receive in the WebAPI's log files? I suspect that the account you are using does not have permissions to the `demo_security` table to query for the credentials.

**Comment by ambuj369** [comment]
Hi @anthonysena 
Here are the changes I made.
1. Added a new table under webapi schema as users.
2. users table consists of following columns - username,password,firstName,middleName,lastName
3. added entry in that table for ohdsi_app_user as username and its password
4. used the same credentials in Settings.xml file to build .war file
5. Prepared the build for webapi and atlas, deployed under tomcat with changes in config-local.js
6. Checked to login - WORKED but no access to any of the Atlas features
7. From sec_user_role, assigned role_id 2 (admin) to ohdsi_app_user
8. Reload Atlas, encountered errors and unable to login, after clicking submit on credentials form, it keeps on loading something.
Attaching all the relevant screenshots for you to refer. 
Please suggest
![Screenshot from 2019-05-22 17-12-40](https://user-images.githubusercontent.com/47858365/58172417-29e0c800-7cb6-11e9-83cf-c4b5a97418cf.png)
![Screenshot from 2019-05-22 17-13-08](https://user-images.githubusercontent.com/47858365/58172418-29e0c800-7cb6-11e9-81c7-7b0c67c22c32.png)
![Screenshot from 2019-05-22 17-13-35](https://user-images.githubusercontent.com/47858365/58172419-29e0c800-7cb6-11e9-9d47-069722b10ac6.png)
![Screenshot from 2019-05-22 17-13-39](https://user-images.githubusercontent.com/47858365/58172420-29e0c800-7cb6-11e9-9dad-b2bd9fd8cc54.jpg)

After changing permission  to Admin (2)  in sec_user_role table.
![Screenshot from 2019-05-22 17-23-31](https://user-images.githubusercontent.com/47858365/58172445-4a108700-7cb6-11e9-9b31-26a4c28088fe.png)


Thank you
- Ambuj

**Comment by anthonysena** [comment]
>7\.From sec_user_role, assigned role_id 2 (admin) to ohdsi_app_user

OK - good news is that you were able to log in successfully and step #7 from your list corresponds to the wiki instructions here: https://github.com/OHDSI/WebAPI/wiki/Atlas-Security#defining-an-administrator

> 8\. Reload Atlas, encountered errors and unable to login, after clicking submit on credentials form, it keeps on loading something.

I'm not clear on what you mean by 'reload atlas, encountered errors' in the statement above. Once you have added the entries to the `sec_user_role` table for the ohdsi_app_user account, you should be able to log out, log back in and then pick up from this point in the wiki: https://github.com/OHDSI/WebAPI/wiki/Atlas-Security#manage-roles-and-permissions. That will allow you provide your account with privileges to access the different interface elements. The fact that you cannot log in after you were able to do that successfully is a bit strange. Are you receiving any errors in the WebAPI logs?

**Comment by ambuj369** [comment]
hi @anthonysena 
Unfortunately, webapi.log is not logging anything so won't be able to provide results.I used the method as mentioned here to capture the logs but no luck.

/tomcat/bin> catalina.bat run > ..\logs\webapi.log 2>&1

For step 8, I signed out of the page and logged back in.
sec_user table have > id = 1002, login = ohdsi_app_user
sec_user_role table have >id =1009,user_id = 1002, role_id = 1000
not sure why I am not able to login.

**Comment by chrisknoll** [comment]
Hi, All, just want to add a comment here:

> Added a new table under webapi schema as users.

While you can get this to work, the way the basic security was set up was that the user database would be stored in an _external database_.  You really should not be adding any custom tables to the webapi schema since that schema is used by WebAPI functions, and we do not want to run into any table name conflicts.  So, if you can set up a separate database to store that user table, that would be preferred (and you specify the separate DB url and user/password in the security settings part of the WebAPI).  

if you must put it in the same database as WebAPI, I would create a new schema and put the login tables in that schema.  The point is to separate those tables from the webAPI schema.

**Comment by ambuj369** [comment]
So just to add and confirm,
The code to perform the authentication expects the password from the user table.
If, a new schema is created for logins, what all changes are expected to be done in settings,xml? Also, the permissions are suppose to be assigned from sec_role table in webapi schema. Will it affect anything is the permissions are pulled from webapi?

**Comment by anthonysena** [comment]
@ambuj369 - I agree with @chrisknoll's recommendation regarding the location of the `demo_security `table. The wiki does recommend this at the top of the "Basic Security Configuration" page. 

To your questions:
- If a new schema is created for logins, what changes are required in settings.xml? Those are described in the wiki with these parameters:
```
<security.db.datasource.url>jdbc:postgresql://localhost:5432/security</security.db.datasource.url>
<security.db.datasource.driverClassName>org.postgresql.Driver</security.db.datasource.driverClassName>
<security.db.datasource.schema>ohdsi</security.db.datasource.schema>
<security.db.datasource.username>ohdsi</security.db.datasource.username>
<security.db.datasource.password>ohdsi</security.db.datasource.password>
<security.db.datasource.authenticationQuery>select password from ${security.db.datasource.schema}.demo_security where email = ?</security.db.datasource.authenticationQuery>
```

The `security.db.datasource.url` allows you to specify a different database connection and the other parameters allow you to control the schema and credentials used to access the `demo_security` table. WebAPI will use this for authentication; it will then use the sec_* tables to authorize that user to different parts of the application.

I'm really unsure why you cannot log in after providing a role to the user. Could you try removing the role, as was done when it originally worked, to confirm that you can log in after that? 

And for the logging: have you tried stopping tomcat so that it can write to the log file? I forget if it buffers the output and only writes to the log after a certain amount of activity.

**Comment by ambuj369** [comment]
Ok, @chrisknoll @anthonysena 
Please correct me if I misinterpreted here.
Basic security link I followed - 
https://github.com/OHDSI/WebAPI/wiki/Basic-Security-Configuration
1. Within page the changes in settings.xml says nothing about a new schema, it still says ohdsi for url
2. Authentication query here is querying demo_security table for password
![BS](https://user-images.githubusercontent.com/47858365/58179402-c2cb0f80-7cc5-11e9-8bdf-78f925c76125.jpg)

3. While checking the code which authenticates the credentials looks for "user" table as shown:
![Code](https://user-images.githubusercontent.com/47858365/58179451-daa29380-7cc5-11e9-887f-4e412f1d2dc8.jpg)

So here is what I am going to do-

1. Remove the "user" table in "webapi" schema and revertchanges made to any of other sec_* table
2. Create a new schema "security" with table "user" and "demo_security"
3. "user" table will have username,password,firstname,middlename,lastname columns
3. settings.xml will have "security" schema and username/password for the "security" schema
4 . Build the .war file and deploy

Questions: 
a) Calling "demo_security" table in settings.xml with "security" schema will work ? or do I have to create the "demo_security" in "webapi" schema?
b) As code looks for "user" table, so it will look for "security" schema rather than "webapi" ?

Please correct me if my assumptions to move ahead are correct. Because I feel that code and xml won't go properly together this way.I may be wrong so a detailed advice will help me to achieve the security part.

Thank You

**Comment by ChavanShweta** [comment]
I think there are few gaps int he code and documentation:

https://github.com/OHDSI/WebAPI/blob/d416229fe4ce8345e685016c0675daaae0279c81/src/main/java/org/ohdsi/webapi/shiro/realms/JdbcAuthRealm.java#L108


for some reason `this.authentication_query` is never executed. As specially Postgres runs the connection query and postgres logs indicate the connection was successful but the authentication query is never run as the function does not get the query. This can be proved when we hard code the query int he function.

https://github.com/OHDSI/WebAPI/blob/d416229fe4ce8345e685016c0675daaae0279c81/src/main/java/org/ohdsi/webapi/shiro/realms/JdbcAuthRealm.java#L122

There is no were mentioned in the documentation that the `demo_security` should have columns(firstname, lastname, middlename) other than email, password.

Even if the basic security instructions are used for set up. WebAPI keep going to LDAP for user authentication.
![Screen Shot 2019-05-22 at 10 31 26 AM](https://user-images.githubusercontent.com/20832191/58183159-d4d49000-7c7c-11e9-8ab4-ef908cc3b1f7.png)

**Comment by chrisknoll** [comment]
Hi @ambuj369 ,
  From what I can tell from the documentation, you only need 1 table in your security database: a table that stores the email (login) and password.  The instructions indicate to use the BCrypt to get the encrypted password value that you will insert into the security table: https://www.dailycred.com/article/bcrypt-calculator.

I recognize that you found in source code references to some `DEFAULT_` queries that assume the following tables: `users` and `user_roles`.  To be honest, I do not know where those default queries are found, i did a global search int he codebase, and I don't see references to those constants.

It appears that the only thing that's required is the security table (which you can name it anything, you can call it `demo_security`), and that table should contain email and password (per the instructions).

Based on what @ChavanShweta pointed out, the code that uses the authentication is here:

```
        // Old style query is used - only password is queried from database
        if(rs.getMetaData().getColumnCount() == 1) {
            userEntity.setPassword(rs.getString(1));
        } else {
            // New style query - user name is also queried from database
            userEntity.setPassword(rs.getString("password"));
            String firstName = trim(rs.getString("firstname"));
            String midlleName = trim(rs.getString("middlename"));
            String lastName = trim(rs.getString("lastname"));

            StringBuilder name = new StringBuilder(firstName);
            if (!midlleName.isEmpty()) {
                name.append(' ').append(midlleName);
            }
            if (!lastName.isEmpty()) {
                name.append(' ').append(lastName);
            }

            userEntity.setName(name.toString().trim());
        }
```

Simply put: if the authentication query contains 1 column in the result, then it will just use the password column from the result.  If the authentication query contains > 1 column, then it's assumed that the authentication query returns 3 columns: `firstname`, `middlename`, `lastname`.  So, you'll adjust your authentication query to reflect what your security table contains. I believe that there is a bug where the value in the settings.xml `security.db.datasource.authenticationQuery` is not being properly read in to the application settings, which leads to some of the errors reported (causing you to hard-code the query directly in code).

The second problem reported is that with only basic security set up, the authentication calls keep hitting the LDAP authenitication mechanism.  So that's another problem that needs to be looked at.

@pavgra , @gklebanov , can you please chme in on the functionaltiy of the basic security system, and if it may lead to some kind of LDAP calls (maybe there's a LDAP filter that is being applied unintentionally?).

**Comment by chrisknoll** [comment]
Addtional requst:

Since you have made hard-coded changes to the code to work aroudn some of the issues, would you mind adding a debug/logging call around this line:

https://github.com/OHDSI/WebAPI/blob/d416229fe4ce8345e685016c0675daaae0279c81/src/main/java/org/ohdsi/webapi/shiro/realms/JdbcAuthRealm.java#L49

This is where the authenticationQuery is being passed in and should be used for user authenication.  Can you log out what the value is that the code is receiving?  That will help us figure out why you need to hard-code the value.

-Chris

**Comment by ChavanShweta** [comment]
@ambuj369 

![image](https://user-images.githubusercontent.com/20832191/58184392-ffbfe380-7c7e-11e9-9dad-f746c73b254a.png)

Can I ask why all the default query, quering `username` instead of `email`?

![image](https://user-images.githubusercontent.com/20832191/58184583-604f2080-7c7f-11e9-9c82-e17a2f0478da.png)

settings.xml querying to `email` is right.

Also if you are using the postgres I wold recommend putting schema name infront of table name.

**Comment by chrisknoll** [comment]
> Can I ask why all the default query, quering username instead of email?

I think this is not related to the actual problem.  From what I can tell in code, the only query that is used to access the security table (eg: `demo_security`) is the query found in security.db.datasource.authenticationQuery`.  When the password is retrieved from that query, the password is then compared between the authentication request and the password stored for the user.

**Comment by ChavanShweta** [comment]
I don't have user table in any of the schema and it works for me. I might be wrong but from what i learned from the code the username and password or user details are stored in a temp file /user/me on the server.

https://github.com/OHDSI/WebAPI/blob/d416229fe4ce8345e685016c0675daaae0279c81/src/main/java/org/ohdsi/webapi/service/UserService.java#L103

@chrisknoll yes this is right. I tried putting the print statement here and it does gives the actual query Its the point where i pointed before.

**Comment by chrisknoll** [comment]
> from what i learned from the code the username and password or user details are stored in a temp file /user/me json file on the server.

This isn't a json file, but just a HTTP request to fetch the currently authenticated user. The response of this request is a JSON format, but it's not a 'temporary file' as you put it.  Also, this is a call that is made when Atlas first starts up, so it may be reasonable and expected that you get a 403 (unauthorized) message from that endpoint until you authenticate (using basic authentication or otherwise).

> @chrisknoll yes this is right. I tried putting the print statement here and it does gives the actual query. Its the point where i pointed before the query cannot be retrived.

Ok, I'm not exactly clear where it 'can not be retrieved'. If you _are_ seeing the query in the constructor of JdbcAuthRealm, but you _do not_ get that value in the call to `createPreparedStatement` here:
https://github.com/OHDSI/WebAPI/blob/d416229fe4ce8345e685016c0675daaae0279c81/src/main/java/org/ohdsi/webapi/shiro/realms/JdbcAuthRealm.java#L108

Then that is very very confusing...that line of code is basically looking at a local class variable...I don't know how you could get the value in the constructor but then no value in the `createPreparedStatement`. Can you add logging to `createPreparedStatement` just to confirm that you did see a value from the constructor, but you do not see the value inside the method call?

**Comment by ChavanShweta** [comment]
@chrisknoll  so does it need the `user table` ? which schema it should be added? what should be its structure or table shell?
unfortunately, I did not take any screenshot at that time.

**Comment by chrisknoll** [comment]
> so does it need the user table ?
No, I do not think so.  It appears you just need 1 table, with email, password in it.  The name of the table isn't important either, since the table name just needs to match the table name in the `authenticationQuery` field.  If you want to store a firstname, middlename, lastname in it, then you can add those columns to the table, but then your authentication query must return the fields `password`, `firstname`, `middlename`, `lastname`.

> which schema it should be added?
Something other than the WebAPI schema. Keep WebAPI tables separated from any external tables (such as the basic authentication table).

> what should be its structure or table shell?
From the documentation it appears:
```
CREATE TABLE ohdsi.demo_security
(
    email character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default"
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;
```

Add firstname, lastname, and middlename (all character varying(255)) if you want to also capture those values.

> what should be the access permissions on this table?
I think read-only because the authentication only needs to read records out of the table. To add new users for permission, you will directly modify the tables to insert the values (ie: you do not maintain your users anywhere in WebAPI (@pavgra , @gklebanov please confirm).

**Comment by ambuj369** [comment]
@chrisknoll @anthonysena @ChavanShweta @pavgra @gklebanov 
Hello everyone.
Based on the discussion above, I made the following changes in my schema and settings.xml -
1. Created a new database > Security
2. Created a new schema > demo_security
3. Tables under demo_security > email,password,firstName,middleName,lastName
4. Values in table : ohdsi_app_user, password in bcrypt format, test,test,test
5. permissions to table> login name: ohdsi_app_user

![pgAdmin_img](https://user-images.githubusercontent.com/47858365/58250911-0c783080-7d80-11e9-8df2-37f6bfc4b5c6.jpg)

Settings.xml -
![ChangesinSettings](https://user-images.githubusercontent.com/47858365/58251738-fc615080-7d81-11e9-9370-55081356c0f8.jpg)

6. Build war file, build Atlas , deployed on tomcat server
7. opened Atlas. logged in : Bad Credentials
![Atlas_demo](https://user-images.githubusercontent.com/47858365/58257108-dfcb1580-7d8d-11e9-8327-2efcfc29dc49.jpg)

I am tired with all permutations and combinations among schema and permissions. So if there is actually an issue with the code, please let me know as end user will not be able to make required code changes.
Also, please update the WebAPI Security Document located at -https://github.com/OHDSI/WebAPI/wiki/Basic-Security-Configuration
As the link says to create a new database,  but in Settings.xml, it says<security.db.datasource.url>jdbc:postgresql://localhost:5432/ohdsi</security.db.datasource.url>
which is confusing as ohdsi is meant for webapi. There is discrepancy and contradictory statements on links.
Anyone, please confirm if its a bug and will be resolved in next build so I can move ahead.

Thank You
- Ambuj

**Comment by chrisknoll** [comment]
Thanks for all the information Ambuj. With this, someone on the team should be able to replicate the issue.

I agree with you that the documentation under Basic-Security-Configuration is confusing that it implies that you should use the WebAPI database, when a separate database or at least a separate schema should be created. I've opened an issue on the documentation here: OHDSI/webapi-wiki#4.

Thank you for your patience, security is a very complicated concept, and the basic security subsystem probably is an element that hasn't seen a lot of use and therefore documentation/testing could be better on it.

**Comment by ambuj369** [comment]
@chrisknoll 
Thank you for acknowledgment on this issue.
I will consider this as the bug and dropping the "basic security" feature in my solution for now and will wait for further updates on the fixes.

-Ambuj

**Comment by chrisknoll** [comment]
Thanks for the information, @ambuj369 .  As far as SSL goes, SSL is just controlling the encryption over HTTPS to the service.  It should not matter if security is enabled or disabled because whether or not security is enabled, SSL just encrypts communication to the service and doesn't (shoudln't) impact any authentication/authorization function.  You can have SSL set up without security (as you have) or SSL set up with security. You can have SSL _disabled_ with AtlasRegularSecuirty, but **you should not do this because then credentials will be sent in plain text!**

**Comment by ssuvorov-fls** [comment]
@ambuj369

**Comment by ssuvorov-fls** [comment]
@ambuj369 
Hello. 
I've created the new database with the same schema and I can't reproduce error with login
Could you attach your settings.xml and pom.xml

**Comment by ambuj369** [comment]
@ssuvorov-fls 
Yes, attached the files.
[settings.xml.txt](https://github.com/OHDSI/WebAPI/files/3300221/settings.xml.txt)

[pom.xml.txt](https://github.com/OHDSI/WebAPI/files/3300223/pom.xml.txt)

Changed the extension to .txt  as git wasn't supporting xml.

-Ambuj

**Comment by ssuvorov-fls** [comment]
@ambuj369 
could you also give me your ddl for security database (including schema and table)

**Comment by ambuj369** [comment]
@ssuvorov-fls 
DDL for Database:

CREATE DATABASE "Security"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

DDL for schema:
CREATE SCHEMA atlas_security
    AUTHORIZATION ohdsi_app_user;

DDL for table:
CREATE TABLE atlas_security.demo_security
(
    email character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    "firstName" character varying(255) COLLATE pg_catalog."default",
    "middleName" character varying(255) COLLATE pg_catalog."default",
    "lastName" character varying(255) COLLATE pg_catalog."default"
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE atlas_security.demo_security
    OWNER to ohdsi_app_user;

GRANT ALL ON TABLE atlas_security.demo_security TO ohdsi_app_user WITH GRANT OPTION;

**Comment by ssuvorov-fls** [comment]
seems, the problem is in capital letters in the names of the columns - "firstName, "middleName" and "lastName"

**Comment by ambuj369** [comment]
@ssuvorov-fls 
Okay, that makes sense. So rest of the information is correct as per the configuration in settings.xml and schema?

if yes, I will re-create the WebAPI build and test.

**Comment by ssuvorov-fls** [comment]
@ambuj369 
Yes, I can connect to database with your settings

**Comment by ambuj369** [comment]
@ssuvorov-fls 
great, I will do that and post here if I come across any issues.

**Comment by chrisknoll** [comment]
> "firstName" character varying(255) COLLATE pg_catalog."default",
> "middleName" character varying(255) COLLATE pg_catalog."default",
> "lastName" character varying(255) COLLATE pg_catalog."default"

Putting quotes around the column names will force case sensitivity on those.  I wouldn't use quotes around the columns names, just define them just like the email and password columns.

**Comment by ambuj369** [comment]
@chrisknoll @ssuvorov-fls 
Hello,

So here is what I did which failed.
1. Created database Security
2. Created schema atlas_security with Security with tables as username,password,firstname,middlename,lastname
3. inserted values for columns
4. modified settings.xml, attaching here
[pom.xml.txt](https://github.com/OHDSI/WebAPI/files/3320960/pom.xml.txt)
[settings.xml.txt](https://github.com/OHDSI/WebAPI/files/3320961/settings.xml.txt)
5. Prepared WebAPI build
6. Deployed WebAPI.war on tomcat
7. Ran build for Atlas
8. Defined config-local.js
9. Restarted Tomcat Services
10. Tried to open http://localhost:8080/WebAPI/source/sources
![WebAPI_source_sources](https://user-images.githubusercontent.com/47858365/60021951-8d448800-96b0-11e9-8e38-7e871acc5319.png)
11. Opened Atlas
![Atlas](https://user-images.githubusercontent.com/47858365/60022004-a0efee80-96b0-11e9-84f8-e61f37192823.png)

Please let me know what am I doing wrong here guys.

Thank You for your patience.

**Comment by ambuj369** [comment]
@chrisknoll @ssuvorov-fls 
Guys,
I am finally able to use the basic security feature in Atlas. 

Still, there are few missing dots from previous comments.
1. Create database eg. Security
2. Create Schema within it as "atlas_security"
3. Create table as demo_security with DDL as below:
CREATE TABLE atlas_security.demo_security
(
    username character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    firstname character varying(255) COLLATE pg_catalog."default",
    middlename character varying(255) COLLATE pg_catalog."default",
    lastname character varying(255) COLLATE pg_catalog."default"
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE atlas_security.demo_security
    OWNER to ohdsi_app_user;

GRANT ALL ON TABLE atlas_security.demo_security TO ohdsi_app_user WITH GRANT OPTION;

4. In demo_security table I have used the column "username" instead of "email" because username is mentioned within the JDBCAuthRealm.Java code
5. Update the settings.xml for authentication query section -
<security.db.datasource.authenticationQuery>select password,firstName,middleName,lastName from atlas_security.demo_security where email = ?</security.db.datasource.authenticationQuery>
6. Build WebAPI.War file, deployed
7. Open Atlas, able to login with the entries made in demo_security table

Now, Issue-
I am not sure why I am receiving the multiple login options in Atlas window. Attaching the config-local.js file and the screenshot for Atlas login.
[config-local.js.txt](https://github.com/OHDSI/WebAPI/files/3325252/config-local.js.txt)
![AtlasSignIn](https://user-images.githubusercontent.com/47858365/60098610-90ed1300-9773-11e9-95cf-30732e6f8fe6.jpg)

what changes should I do within the file to avoid multiple login options.

Thank You

**Comment by ssuvorov-fls** [comment]
@ambuj369 
You can modify the list of available login options in "js/config/app.js" via the "appConfig.authProviders" parameter

**Comment by ambuj369** [comment]
@ssuvorov-fls
got it. So, in that case if I wish to move over to some other security feature, will that be an issue?
I guess taking a copy and making changes will work.

**Comment by ssuvorov-fls** [comment]
Yes, you can modify it. Just implement the correct backend service

**Comment by ambuj369** [comment]
@ssuvorov-fls 
Awesome. Thank you so much. 
The document for Basic Security needs update :)

**Comment by m3nukim** [comment]
> Thanks for the information, @ambuj369 . As far as SSL goes, SSL is just controlling the encryption over HTTPS to the service. It should not matter if security is enabled or disabled because whether or not security is enabled, SSL just encrypts communication to the service and doesn't (shoudln't) impact any authentication/authorization function. You can have SSL set up without security (as you have) or SSL set up with security. You can have SSL _disabled_ with AtlasRegularSecuirty, but **you should not do this because then credentials will be sent in plain text!**

Actually, I tried with "AtlasRegularSecurity" and "<security.ssl.enabled>false</security.ssl.enabled>". It doesn't work at all. Still getting HTTP 401 error.
But I noticed Atlas with basic security login(login with DB) requests with "https". So I enabled security connection on Tomcat. Now it is working without problem.

I think basic security wiki document needs to mention about SSL.

**Comment by anthonysena** [comment]
Wiki updated to reflect this information.
