### ISSUE TITLE
call to cdmresults fails with 404 if achilles_results table does not exist

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/WebAPI#11]
this is breaking parts of hermes and is not the correct behavior.  for this particular call 

``` javascript

'/cdmresults/{concept id}/monthlyConditionOccurrencePrevalence'

```

if the required achilles schema is missing the webapi should simply return an empty result set with http status of 200.

**Comment by mav7014** [comment]
I'd argue that `500 Internal Server Error` or `501 Not Implemented` are more suitable responses since the server is not correctly/fully set up. It should be up to Hermes or whatever client to figure out how it should proceed. `200 OK` with empty results suggests that the query succeeded when it didn't.

**Comment by anthonysena** [comment]
Closing this since this endpoint no longer exists.
