### ISSUE TITLE
Unify Feature Analysis types constant

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#1206]
Today we have `StandardFeatureAnalysisType` defining `CRITERIA_SET` and `CAST('CRITERIA' AS VARCHAR(255)) as fa_type` in SQLs

**Comment by ssuvorov-fls** [comment]
**The migration will only be applied to undeleted sources.
In case of restoring source this migration will have to be done manually**

**Comment by anthonysena** [comment]
@ssuvorov-fls - sorry for my confusion about some of the pull requests related to closing out this issue. As you'll see in the commit log on master, I merged in the WebAPI changes and then reverted them. If you could please re-open a new pull request for WebAPI based on the `issue-1206-change_criteria_set_fa_type` branch I'd appreciate it.

The reason why I reverted this set of changes is due to the issue I raised: https://github.com/OHDSI/SkeletonCohortCharacterization/issues/16. Once we introduce a new version of the SkeletonCohortCharacterization component that includes https://github.com/OHDSI/SkeletonCohortCharacterization/pull/15, we need to update the pom.xml in `issue-1206-change_criteria_set_fa_type` branch to reference the new changes. Otherwise we will not be able to resolve all of the project dependencies properly.
