### ISSUE TITLE
Heracles reports execution fails for Google BigQuery

### ISSUE THREAD

**Issue by konstjar** [OHDSI/WebAPI#1210]
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
 "code" : 400,
 "errors" : [ {
   "domain" : "global",
   "location" : "q",
   "locationType" : "parameter",
   "message" : "Unrecognized name: istinct at [3:32]",
   "reason" : "invalidQuery"
 } ],
 "message" : "Unrecognized name: istinct at [3:32]",
 "status" : "INVALID_ARGUMENT"
}
2019-06-21 18:59:53.825 ERROR taskExecutor-5 org.springframework.batch.core.step.AbstractStep -  - Encountered an error executing step cohortAnalysisStep in job cohortAnalysisJob
org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL []; SQL state [HY000]; error code [100033]; [Simba][BigQueryJDBCDriver](100033) Error getting job status.; nested exception is java.sql.SQLException: [Simba][BigQueryJDBCDriver](100033) Error getting job status.

Currently the issue is under research if it's environment problem

**Comment by chrisknoll** [comment]
Odd that the unrecognized name is `istinct` as in it should have been `distinct` but the 'd' was dropped?  Any way you can get the actual query that was executed/translated?

**Comment by konstjar** [comment]
The problem was localized in SQLRender with `with @@a (@@b) as (select @@c from @@d)` pattern

**Comment by pavgra** [comment]
The original issue was fixed by https://github.com/OHDSI/SqlRender/pull/175.

However, going further, another problem has been discovered - one of Heracles queries fails for BQ:
![image](https://user-images.githubusercontent.com/10010071/60052832-494b8600-96a4-11e9-9551-6e1bf2b0598f.png)

I assume that the issue here might have the same nature as this one - https://github.com/OHDSI/WebAPI/commit/85d683f75f998347e8d9db2eba53de2e26f8bbf6
