### ISSUE TITLE
Unable to create custom feature - Feature Analyses

### ISSUE THREAD

**Issue by SSMK-wq** [OHDSI/WebAPI#1215]
Hello Everyone,

I did try creating a custom feature 'Systolic Blood Pressure' feature from Measurement domain. But couldn't generate the report successfully. Please find the screenshot and details here in this post (http://forums.ohdsi.org/t/how-to-create-own-features-atlas-characterization-summary-statistics/6944/2) I guess there are similar issues. Not very sure.  Creating this issue based on response from Chris in forum. I have also attached my characterization export from Utilities section. Please note we are using webapi 2.7.1, CDM v5.3 and using Postgresql db. 
[Characterization_export.txt](https://github.com/OHDSI/WebAPI/files/3335243/Characterization_export.txt)

**Comment by SelvaSathappan** [comment]
Still the issue exists in 2.7.2. Please find the characterization.json
[char.2.7.2.txt](https://github.com/OHDSI/WebAPI/files/3342980/char.2.7.2.txt)

**Comment by SelvaSathappan** [comment]
Can you share your characterization json and feature json if it works at your end?

**Comment by anthonysena** [comment]
So, I'm looking at the SYB feature - it is currently defined as a "preset" feature which is the problem. The "preset" refers to those features defined in the FeatureExtraction package. With 2.7.2, we removed the ability for a user to define a preset feature since this was problematic: https://github.com/OHDSI/Atlas/issues/1923#issuecomment-503293776.

Make sure that you are using ATLAS 2.7.2, try to edit the feature and make sure that the 'custom' feature is used. What you had shown here should work from a technical perspective:

https://forums.ohdsi.org/uploads/default/original/2X/a/afa632f31469bd4b64a3bcc97cb208b4874b88de.png

I'd suggest changing the domain to 'measurement' which will help when you are trying to find this feature from the feature selector.

From a clinical perspective, I'd ask: what is it that you trying to characterize regarding Systolic Blood Pressure? Using the definition that you provided in the screenshot, this will give you a distribution of the total Systolic Blood Pressure measurements taken for patients in your diabetes cohort in all recorded time. If you are after the measurement's value distribution, this is still a gap as described in this issue: https://github.com/OHDSI/WebAPI/issues/1220

**Comment by SelvaSathappan** [comment]
Okay, I would like to get the min, max, std distribution. Is this possible now? Like for any other continuous variable, we get some summary statistics. I would like to have the same for this and few more measurement values as well. I tried with measurement domain as well but it still didn't work

**Comment by SelvaSathappan** [comment]
![image](https://user-images.githubusercontent.com/30723825/60398240-b1a8d480-9b88-11e9-8683-747a6b53d37f.png)

**Comment by SelvaSathappan** [comment]
But custom feature, doesn't let me "save"?

**Comment by anthonysena** [comment]
Let me try to respond to your individual posts here:

Post 1:
> Okay, I would like to get the min, max, std distribution. Is this possible now? 

Yes but keep in mind: you are getting the min, max, std dev, etc of the measurement record counts, not the values recorded for those measurements. 

Post 2:

Yes, this looks like the right way to create a custom criteria feature.  Is it working for you?

Post 3:

Can you supply a screen shot? Post 2 looks like you were able to save things since the delete button is active.

**Comment by SelvaSathappan** [comment]
1) Are custom and criteria any different?  Can you help me understand?

2) Can you share your characterization for measurement SYB that you did, so I can actually see what I am doing it wrong? It would be helpful

**Comment by SelvaSathappan** [comment]
Can you also share a screenshot of how the output looks here or in the forum? So that, I can refer

**Comment by SelvaSathappan** [comment]
![image](https://user-images.githubusercontent.com/30723825/60398578-9e980380-9b8c-11e9-99ef-9e9136052e38.png)

As shown in the screenshot, it's missing one of the concepts/measurements which we have in our table? Can I know what is the issue? I have also posted in forum https://forums.ohdsi.org/t/atlas-issue-with-characterization-display/7289

**Comment by anthonysena** [comment]
> Are` custom and criteria any different? Can you help me understand?

They are different in that the criteria allows you to use the Atlas interface to define your feature criteria; the custom allows you to enter SQL. I'd recommend sticking to the criteria builder

> Can you share your characterization for measurement SYB that you did, so I can actually see what I am doing it wrong? It would be helpful. I mean which can help me reproduce here

Yes, here you go: [issue-1215-cc.txt](https://github.com/OHDSI/WebAPI/files/3343038/issue-1215-cc.txt). Here's the screenshot of the custom feature:

![image](https://user-images.githubusercontent.com/12902366/60398760-1f71e380-9b2a-11e9-85e5-c0590cba5c3b.png)

And the concept set:

![image](https://user-images.githubusercontent.com/12902366/60398765-37496780-9b2a-11e9-96f4-a264714e7222.png)

You can ignore the fact that I kept this custom feature in the 'condition' domain - I was simply attempting to emulate what you had posted in the forums. It shouldn't have an impact on the function of the feature.

> As shown in the screenshot, it's missing one of the concepts/measurements which we have in our table? 

This may be a different issue all together in which case I'd suggest you post this as an issue to GitHub here. That said, could you take a look into your results schema, find the table `cc_results` and then see if the concepts you'd expect to appear in ATLAS appear in that table? I'm thinking they may be filtered out since they are not present above a certain threshold.

**Comment by SelvaSathappan** [comment]
When I make use of your json, do I have to create concepts, or it will automatically be created?

**Comment by anthonysena** [comment]
When importing the characterization, the feature and its dependencies should be created. It is worth double checking that to make sure that the feature has all of the design elements if you are missing data.

If the results are empty, it could be due to missing data - your cohort definition doesn't yield patients on the database that I tried. With another cohort though, I was able to make this feature work.

**Comment by SelvaSathappan** [comment]
Hi, one quick question. We generate covariates for our final cohort (cohort in results table). So wouldn't we expect to see same number of records for all features?  As shown in the below screenshot, you can see that count values are different. Does Atlas automatically reject null values/values below certain threshold?

![image](https://user-images.githubusercontent.com/30723825/60399258-73b1ad80-9b94-11e9-9cbd-0f0d0a556c80.png)

**Comment by anthonysena** [comment]
Closing due to age but please re-open if this issue still persists on the latest code base.
