### ISSUE TITLE
Didn't work maven building in version:2.72 WebAPI 

### ISSUE THREAD

**Issue by PARKCHANGHYUN-dev** [OHDSI/WebAPI#1233]
Hi 
I'm a Developer for  Atlas Settings .

I want to  make "WebAPI.war" file  of 2.72 version  to maven build using "ORACLE" DBMS.

 When I build  "WebAPI" 2.70 version, it is well working .

But  When I build  "WebAPI" 2.72 version, it make error.

Under image is a chapture of error. please let me know how can I to do. 

![image](https://user-images.githubusercontent.com/53026389/61423358-73623200-a94a-11e9-97ac-075dca9408c8.png)

**Comment by anthonysena** [comment]
Hi @PARKCHANGHYUN-dev - sorry for the delayed response. We appreciate your pull request but wanted to ask if you had tried this step from the wiki: https://github.com/OHDSI/WebAPI/wiki/WebAPI-Installation-Guide#oracle-specific-configuration. Presumably, if you have downloaded the appropriate JDBC Jar file from Oracle and install it into your local repository, you should not need to update the pom.xml. Please let me know if that works and if so, we can look to close this issue and the related pull request. Thanks!

**Comment by ParkChanghHyun** [comment]
At that time , I already tried this step from the wiki: https://github.com/OHDSI/WebAPI/wiki/WebAPI-Installation-Guide#oracle-specific-configuration.

But that's didn't work ,so I tried to update the pom.xml. 

thanks~!

**Comment by anthonysena** [comment]
Sorry to hear that those instructions did not work for you @ParkChanghHyun. I reviewed the changes between WebAPI v2.7.0 and v2.7.2 and noticed that we removed the maven `<repository>` entries that referenced the Odysseus repo which is where the Oracle ojdbc was likely referenced. That may be why it worked for you on v2.7.0 and failed on v2.7.2. Also, since this issue is a bit old, I'd suggest you use v2.7.4 as that is the latest version of WebAPI.

I found this StackOverflow article that may be of help here: https://stackoverflow.com/questions/9898499/oracle-jdbc-ojdbc6-jar-as-a-maven-dependency. In reading through that link, you will still want to download the Oracle driver to your machine. From there, you can try a different Maven command for installing the ojdbc6 JAR into your local maven repository:

````
mvn install:install-file -Dfile={full path to ojdbc6.jar} -DgroupId=com.oracle -DartifactId=ojdbc6 -Dversion=12.1.0.1 -Dpackaging=jar  
````

If you could give this a try and let me know the results, that would be helpful for us so we can update the wiki. Thanks!

**Comment by ParkChanghHyun** [comment]
@anthonysena  
Hi anthonysena!  Thank you for your coment!

I'll talk about 3 kinds of matter.

1.  This command didin't work.
mvn install:install-file -Dfile={full path to ojdbc6.jar} -DgroupId=com.oracle -DartifactId=ojdbc6 -Dversion=12.1.0.1 -Dpackaging=jar  
 I think maven repository didn't have ojdbc6 version.

2. In oracle version 12c (12.2.0.1),  It is nessesary more than ojdbc7.(I use ojdbc8).
When I use ojdbc6 "Log-In"Function didn't work in Atlas.

So!!! I do locally install ojdbc8 in maven. 

3.  Last, Sorry I can't close this issue.
Because my email is expired.

that's all~! 
thanks~!

**Comment by anthonysena** [comment]
Thanks @ParkChanghHyun for this update. Just to confirm: you were able to install the ojdbc8 driver via maven using a command similar to this one:

````
mvn install:install-file -Dfile={full path to ojdbc8.jar} -DgroupId=com.oracle -DartifactId=ojdbc8 -Dversion=12.1.0.1 -Dpackaging=jar 
````

Did you also change the pom.xml? Just curious in case others run into the same issue with their configuration.

**Comment by ParkChanghHyun** [comment]
@anthonysena    
I try this 
`mvn install:install-file -Dfile={full path to ojdbc8.jar} -DgroupId=com.oracle -DartifactId=ojdbc8 -Dversion=12.1.0.1 -Dpackaging=jar `
 command line  but it didn't works.

this is a error log.

![image](https://user-images.githubusercontent.com/45930454/71220027-718e0780-230a-11ea-819e-91194ac4c20d.png)

**Comment by anthonysena** [comment]
@ParkChanghHyun - earlier you mentioned:

> So!!! I do locally install ojdbc8 in maven.

Could you describe how you did this if the maven command I supplied does not work? I'd like to make sure this is updated in the documentation and potentially the approach we use in the pom.xml. Thank you!

**Comment by ParkChanghHyun** [comment]
Sorry to late.
First of all Happy new year~! @anthonysena 

I have two solution about installing 'ojdbc8'.

# First,  just change "pom.xml" file like  I above mentioned .
『
# Second, install 'ojdbc8' in local maven repository. 
(I will show the step of installing    'ojdbc8' in local maven repository.)

1.  "ojdbc8.jar" file download in internet (like this URL https://www.oracle.com/database/technologies/jdbc-ucp-122-downloads.html)

2. mvn install:install-file -Dfile={ """Path/to/your/ojdbc8.jar"""}
      -DgroupId=com.oracle -DartifactId=ojdbc8 -Dversion=12.2.0.1 -Dpackaging=jar

3. fix the pom.xml (like bellow image)
![image](https://user-images.githubusercontent.com/45930454/71652071-06125400-2d66-11ea-86af-bae934da4845.png)


that's all. It is a method how to install ojdbc8 local repository.

』

p.s But when I check recent online MAVEN repository,   ojdbc8 is exists!
I tihnk it updated recently

Thanks~!

**Comment by anthonysena** [comment]
@ParkChanghHyun - Happy New Year! Thanks for sending along this information. I was just reviewing this thread again and noticed that in [this comment](https://github.com/OHDSI/WebAPI/issues/1233#issuecomment-567735259) you had not replaced the token `{full path to ojdbc8.jar}` in the maven command to use the full path to the driver which will cause an issue. 

For the purposes of this example, let's say you have downloaded the Oracle 8 driver to: C:\oracle\ojdbc8.jar. The command should then be:

````
mvn install:install-file -Dfile=C:\oracle\ojdbc8.jar -DgroupId=com.oracle -DartifactId=ojdbc8 -Dversion=12.1.0.1 -Dpackaging=jar
````

Could you give this a try and see if this works? Appreciate your help in troubleshooting this issue!

**Comment by ParkChanghHyun** [comment]
@anthonysena 
When I download "Oracle 8 driver" and that's driver located in 'C:\oracle\ojdbc8.jar' directory. It is well working!

**Comment by anthonysena** [comment]
Thanks for confirming @ParkChanghHyun! So if I understand things correctly, once you've updated the maven command, the build works properly and you no longer need to change the pom.xml that was submitted via #1333? If you agree, could you close out this issue and the pull request? Thank you!

**Comment by ParkChanghHyun** [comment]
Thanks @anthonysena !!
I totally agree with you! 

But I can't close the Issue.
Because I can't log in the "@PARKCHANGHYUN-dev " any more.
@PARKCHANGHYUN-dev's  Email adress expire. 

So if you can close my Issue, could you close it?
