### ISSUE TITLE
Exporting and Importing Cohorts Between Distinct Databases

### ISSUE THREAD

**Issue by tnovo** [OHDSI/WebAPI#127]
Hello, 
At University of Aveiro we are working in the EMIF European Project, and including OHDSI tools in our framework. Within the scope of this works we are now aiming to allow import and export of cohorts between databases, so that we can share cohort definition between distinct ATLAS instances.

We realized that we need to export/share Cohorts and Concepts Sets. 
Our problem is how can we map different concepts/domains/relationships on different Vocabulary ids, because the same vocabulary entry can have different IDs across multiple databases.

Can you give us some advice on the best approach ?

**Comment by anthonysena** [comment]
@tnovo - I'm going to close this out since this issue is quite old. As part of closing this, I'll attempt to answer the points you raised above:

> We realized that we need to export/share Cohorts and Concepts Sets.

[ATLAS](https://github.com/OHDSI/Atlas) provides a UI for importing/exporting cohorts & concept sets.

> Our problem is how can we map different concepts/domains/relationships on different Vocabulary ids, because the same vocabulary entry can have different IDs across multiple databases.

The concepts represented in the standardized vocabularies will not change. If you find an instance where this is not the case, please report this to the OHDSI forums here: https://forums.ohdsi.org/c/vocabulary-users
