### ISSUE TITLE
Basic security | bcrypt calculator link not working | other options

### ISSUE THREAD

**Issue by ChavanShweta** [OHDSI/WebAPI#1350]
> Next you will need to insert a sample record that will contain our demonstration username and password. The password is encrypted using BCrypt. You can create your own username and password or use the sample insert statement provided below where we have already encrypted the password 'ohdsi' for the user named 'ohdsi'. To create a different password hash using BCrypt you can use the following web site:

https://www.dailycred.com/article/bcrypt-calculator

This link is not working for me anymore. other options to created the password hash? how many rounds are set for the bcrypt decrypt. I tried other link to create the bcrypt hash and WebAPI was not able to decrypt the hash.
![Screen Shot 2019-10-17 at 9 48 29 AM](https://user-images.githubusercontent.com/20832191/67014915-a5a73b00-f0c3-11e9-9c09-4408556de56b.png)

**Comment by anthonysena** [comment]
Hi @ChavanShweta - you are correct - it looks like the BCrypt calculator has been taken offline. We'll work to update the wiki with this link:

https://www.browserling.com/tools/bcrypt

Thanks to @ambuj369 since it was mentioned here: https://github.com/OHDSI/WebAPI/issues/1341#issuecomment-538410166
