### ISSUE TITLE
Bearer token timeout for DB authentication

### ISSUE THREAD

**Issue by ambuj369** [OHDSI/WebAPI#1385]
Hello,

I am testing Atlas with 100 concurrent users using Apache JMeter scripts. 

All users are logging in with a gap of 10 seconds with think time of 10 seconds. 

The bearer token is getting expired in defined think time and leaving errors behind.

Is there a way in settings.xml or pom.xml to update the bearer token timeout?

Environment: Linux
Database: PostgreSQL
WebAPI version: 2.7.4
Atlas version: 2.7.4
Security: DB authentication

Thank You

**Comment by anthonysena** [comment]
@ambuj369 - The token time out is controlled by the `security.token.expiration` setting:

https://github.com/OHDSI/WebAPI/blob/master/pom.xml#L64

It is currently 43200 seconds (12 hrs). I'm not sure why your test is failing there but I'm going to note this issue for the 2.8 release since I could not find a reference to this setting in the documentation.

**Comment by anthonysena** [comment]
Wiki updated to reflect this information.
