### ISSUE TITLE
Use a unified "resultset" table design for storing OHDSI tools/Atlas module generated results

### ISSUE THREAD

**Issue by leeevans** [OHDSI/WebAPI#140]
We had a good discussion in the recent Architecture Work Group call on unifying the Atlas generation UI. This is a proposal for the group to also consider unifying the approach for storing generated results in the results database.

Currently we have different results database tables (with different columns defined) for each OHDSI tool/Atlas module that generates some form of results. e.g. Achilles, Heracles, Penelope, feasibility study etc. 

Below is one suggestion for a more uniform approach to handling generated results:

We could introduce a single RESULTSET table that generically allows for say 26 columns of results to be stored. We would replace the existing tables that store results with a single new RESULTSET table similar in concept to the existing ACHILLES_RESULTS table but with each varchar(255) column just named a single letter A..Z (like spreadsheet columns).  There would also be a new associated RESULTSET_META table that contains the metadata for each result set. 

We can consider the concept of a 'resultset' as similar to a generic spreadsheet worksheet or an R data frame. 

The RESULTSET_META table could contain the following kinds of attributes for a generated resultset:

resultset_id (unique),
source_id (from source table - identifies the source dataset in the CDM used to generate the results)
resultset_type_concept_id (e.g. a new concept to represent the type of resultset: feasibility study, heracles cohort analysis, achilles dataset analysis, achilles heel counts, penelope source counts, penelope negative control counts, etc)
field_name_list (a varchar string of comma separated result field names to label each result column)
field_types_list (e.g. a varchar string of comma separated result field data types to help with later casting from the varchar result columns)
resultset_description
generator_description (description of algorithm/process that generated the resultset)
job_execution_id (id of the job that created the resultset(s))
job_execution_step_id (Do we also need this if a job with multiple steps can create multiple resultsets?)
generation date
organization_id (useful for OHDSI network study aggregate statistics de-identified resultsets)
owner_id

Benefits
1) Atlas module/OHDSI tool developers can introduce future new analytics capabilities that generate results, without having to create additional analysis specific results tables. 
2) OHDSI network study R/SQL code developers can generate de-identified study aggregate stats results using the 2 proposed resultset tables. One-time creation of the two resultset tables would then be a prerequisite for running OHDSI network studies but every study wouldn't have to define and create it's own study specific output tables. 
3) It will simplify the results database creation/migration of OHDSI results tables.  (fewer tables to manage).
4) Can create a new standard resultset Atlas component to re-generate, delete, search for and describe any resultset. It would make use of the RESULTSET_META table in each results database. 
5) Can create a standard Atlas component to view the contents of any result set as a HTML table (showing the column names in the field_names_list column in the RESULTSET_META table). That component would need to handle large resultsets through paging/filtering.
6) Can create a new WebAPI service to serialize/deserialize any resultset from the RESULTSET table to a zipped file for export/import (if user security allows) - can write/read json and csv formats. 
7) Can support comparisons between the same type of resultsets.
8) Can support storage of results generated from any arbitrary R function or SQL code executed in a batch job that can write out it's results to the proposed two resultset database tables.
9) Support for interop between Atlas modules/OHDSI tools. One module/tool can potentially generate a new resultset by reading and further processing an existing resultset created by another tool (or job step) in a 'pipeline' approach.

Some challenges
1) This would be a fundamental change in the OHDSI architecture for generating results - with major impact on the existing code base and a large refactoring effort required. At a minimum it should be considered for inclusion in future code refactoring efforts.
2) One time migration of existing results to the new resultset tables is needed - migration script required.
3) Additional performance overhead of casting result set fields from varchar to int/float/date etc when using the results. Would need to test and quantify performance impact on large resultsets.
4) There is some practical limit on number of result columns supported. e.g. Are 24 result columns enough?
5) In the suggested implementation there is a potential performance impact of storing all results in a single database table.  We can mitigate this using DBMS table features to partition or distribute data on columns like resultset_type_concept_id. This would require redundantly including column(s), e.g. resultset_type_concept_id, in the RESULTSET table for partitioning/distribution usage.

**Comment by chrisknoll** [comment]
Hi @leeevans , thanks for writing all this up.  Really well thought out and lots of things to consider.

I'm sorry to be a voice of dissent, but different types of analysis will have different types of attributes captured.  Even in achilles, there's not one  single results table: there's a achilles_results table which stores simple statistics that can be stratified by up to 5 stratum (stratum_1, stratum_2, stratum_3, stratum_4, stratum_5 in the table) and a count, but there's also an achilles_results_dist table which contains distribution information about a particular analysis (min, max, avg, stddev, p10, p25, p50 (median), p90, number of members in the strata, etc.  And there's Achilles_heel that stores a analysis_id, message and row_count.  So 3 different tables for 3 distinct purposes.

I don't think it would be beneficial to try to normalize all 3 of these different types of tables into a 'universal results' table.  All the columns would be varchar() so that you'd have flexibility in the data type, but that should be a red flag to any database designer.  the column type is very important for speed of query, storage of data, and validation of the type of data that belongs in a column.  Plus having an abstract list of 26 column names where you need to know what a particular column means for a particular type of analysis is a challenge too keep organized. 

Now, could we have a few distinct types of tables for results that would capture the specific elements of data that can be meaningful set of columns. For example, the achilles_results table is really a count_by_strata type of structure.  The results_dist table is a sort of dist_by_strata result.  The heel table is simple but by having it separate we can extend that table to support the notion of 'drill-downs' without having to consider what all other results would be impacted by this change (as would be the case if there was just a single table storing all results together).

I understand the appeal of the single table, you've laid out the pros above, and it sounds like there's just so many pros to it, but the reality is (from my experience) is that an abstract table doesn't actually enforce any structure: people can use it in any way they see fit. this leads to inconsistent implementation, complicated documentation and painful maintenance of code (because by chaing one usecase of writing data into the table, you may have to consider all the other use cases for writing to this table in order to make a simple enhancement (see heel drill-through above).

**Comment by leeevans** [comment]
Hi @chrisknoll thanks for the feedback!  Very helpful and informative as always.

I can unpack this proposal into a few separate pieces.

1) There appears to be some overlap in how we store results in the results database today.  e.g. compare the achilles_analysis table with the heracles_analysis table. There may be opportunities to refactor. Perhaps some developer guidance/standards around the creation of new results tables or re-use of existing results tables could also be useful.

2) There is a range of possible implementations for handling generated results where at one end (where we are today) is a separate set of custom output tables for each Atlas module/OHDSI method. I guess I went to the opposite extreme where I considered the results of any analytical process as just a set of generated metrics/measures that can be stored in a generic 'resultset' table. Your suggestion about creating a few distinct types of tables for generated results is a good option somewhere in the middle. 

3) I agree with your discussion on the benefits to using meaningful data types. I'm open to better suggestions for persisting a generic result set in a database. 

4) Implementation of a generic resultset table would enable an Atlas admin to generate new analytic metrics/measures in an agile way while still following a standard workflow. They would submit their SQL as a batch job (translated by SqlRender). The last step in the SQL code would persist the results to the generic resultset table in the results database. Generation of clinical quality measures or execution of algorithms to generate safety signal values for HOI/drug pairs might be two example use cases but the approach could support the generation of any kind of analytical result.

**Comment by anthonysena** [comment]
I'm closing this issue due to age - the idea here are still important and valid but the platform has progressed by using a well-defined results data model that is distinct from other OHDSI tools (i.e. HADES). If we need to revisit this idea, we can re-open this issue.
