### ISSUE TITLE
Atlas jobs hang on Starting/Stopping statuses

### ISSUE THREAD

**Issue by olga-ganina** [OHDSI/WebAPI#1424]

**Comment by wivern** [comment]
There [ThreadPoolTaskExecutor](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/scheduling/concurrent/ThreadPoolTaskExecutor.html) is used to job tasks management. It is responsive to start new job in a pooled thread, track thread state, and store jobs in a queue when the maximum number of threads has reached.

Option | Version | Description | Default value
-- | -- | -- | --
spring.batch.taskExecutor.corePoolSize | 2.5 | Initial size of the thread pool, | 10
spring.batch.taskExecutor.maxPoolSize | 2.5 | Maximum number of threads in the pool | 20
spring.batch.taskExecutor.queueCapacity | 2.7.6 | Queue capacity, also affects to queuing strategy, see details below | MAXINT
spring.batch.taskExecutor.threadGroupName | 2.7.6 | The name of a thread group, useful to tracking job threads |  
spring.batch.taskExecutor.threadNamePrefix | 2.7.6 | The prefix that would be added to thread name, useful to tracking job threads |  

The default behavior is the Unbounded queue strategy. This means no more threads could be busy than `corePoolSize`. Reaching the number of threads to `corePoolSize` will cause new tasks waiting in the queue.

Setting the `queueCapacity` to 0 will switch strategy to Direct handoff which means constructing a new thread when no more available threads. A number of threads could not be more than `maxPoolSize`, when `maxPoolSize` is reached tasks will be rejected. So `maxPoolSize` value should be enough to avoid task rejection. More details available in the [ThreadPoolExecutor](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ThreadPoolExecutor.html) documentation.

Since 2.7.6 ThreadPoolTaskExecutor bean is exposed as a JMX bean. This provides to monitor thread pool state using any JMX tool such as JConsole.
