### ISSUE TITLE
estimations are missing after upgrade to 2.7.6 from 2.5.2

### ISSUE THREAD

**Issue by chris2nd** [OHDSI/WebAPI#1498]
### Expected behavior
Estimations that users have designed should still available after upgrading Atlas and WebAPI from 2.5.2 to 2.7.6

### Actual behavior
Estimations are missing, while other research designs such as Characterizations, Cohort Pathway, Prediction etc are still available

### Steps to reproduce behavior
1. Setup v2.5.2 
2. Create a estimation 
3. Stop v2.5.2
4. Upgrade to v2.7.6 with same OHDSI schema 

IMHO, It seems estimations are stored in cc_XXX tables in v2.5.2, however, they are stored in table name called "estimation" in v.2.7.2

**Comment by anthonysena** [comment]
You are correct - this also applies to prediction designs done in v2.5.x. Let me explain why this was done: the estimation/prediction features developed for 2.5.x were limited in that they only allowed for design of a single target cohort (in the case of an estimation a single comparator) and a single outcome. Additionally, these designs only allowed for configuration of a subset of all available features that are offered up by OHDSI/CohortMethod and OHDSI/PatientLevelPrediction.

In v2.6.0, we made a big change in the way that we allowed users to specify an Estimation or Prediction study. Since v2.6.0, we support multiple Target cohorts and Outcomes in addition to multiple analysis settings. This was a breaking change but a necessary one to allow for more robust analysis specifications to occur in ATLAS. When we undertook this set of changes, I decided to leave behind the legacy "cca" and "plp" tables so that users could still access those designs if needed. The process of converting these legacy designs to the new structure was not trivial and it would likely be easier to re-create those designs from scratch vs. trying to create a migration script.

Given our current focus on trying to finish up v2.8 to then allow us to focus on the next major release (v3.0), I'm going to note this as an issue we won't fix but I think it is helpful for people that may have the same question to know the context for why this decision was made.

**Comment by Geunhae-Lee** [comment]
I understand that sometimes big changes on concept makes throwing away some legacy code.
But in that case, It is better to have translation tools. 
Yes. as you mentioned, It might be easier to do by manual. However designing with some features such as negative controls becomes mendatory in v2.7(not in v2.5), so it is impossible to generate same design. And even worse, I have over 500 estimations to tranlsate manually.😔

And you mentioned that you leave legacy tables to keep them accessible. By this, you mean accessing thru DB table?(not in atlas 2.7)

Thank you for your response.

**Comment by anthonysena** [comment]
@Geunhae-Lee - sorry to hear that there are so many assets to move. To answer your question: the legacy WebAPI table that holds all of the previous estimation studies is still in your WebAPI DB: the table "cca" will contain all of the attributes used to configure the study with references to the cohort IDs found in the fields: `treatment_id`, `comparator_id`, `outcome_id`.

If you have plans to migrate your work from the old format to the new format, that would be a great contribution for the OHDSI community in case others find themselves in this situation.
