### ISSUE TITLE
Use of results_database_schema and target_database_schema during cohort construction

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/WebAPI#1515]
https://github.com/OHDSI/circe-be/blob/a9f12090270c3bffd46fd5a98e02ca48ccdec44a/src/main/resources/resources/cohortdefinition/sql/cohortInclusionAnalysis.sql#L1

https://github.com/OHDSI/WebAPI/blob/0dc6dbd756eae96c50ca6cdfac57aa8883273705/src/main/resources/resources/cohortdefinition/sql/copyGenerationIntoCohortTableSql.sql#L1

We seem to be using both target_database_schema and results_database_schema in cohort construction. It looks like we use target_database_schema for cohort-construction, and results_database_schema for cohortInclusionAnalysis. Would it be possible to use either target_database_schema or results_database_schema, but not both?

resulted in unanticipated error here https://github.com/OHDSI/CohortDiagnostics/issues/35

**Comment by anthonysena** [comment]
@gowthamrao - I think having a consistent key for the schema is the right idea. However, I don't think we'll tackle this yet; please plan to set both the `target_database_schema` and `results_database_schema` to the same value for now.

**Comment by chrisknoll** [comment]
The reason is that circe-be can be used in contexts outside of WebAPI, so 'targetSchema' was the abstract name given for that.  You can imagine that even in an analysis package, you may have separate schemas for your cohorts and your results, so in one case the 'target' schema would be the cohort schema, and in another case (WebAPI) we use 'results'.

In the WebAPI script, the only schemas it knows about is the results and cdm schema, so it made sense to call it that.
