### ISSUE TITLE
Full Analysis reports fail in BigQuery

### ISSUE THREAD

**Issue by konstjar** [OHDSI/WebAPI#1618]
It looks like cost analysis fails on some datasets:

```
CREATE TABLE synpuf_110k_results.bzcqp7rkraw_cost_4020
 AS
SELECT
c1.cohort_definition_id,
  c1.subject_id,
  vo1.visit_occurrence_id,
  vo1.visit_concept_id,
  vo1.visit_type_concept_id,
  cst1.cost_concept_id,
  cst1.cost_type_concept_id,
  vo1.visit_start_date,
  cost
FROM
synpuf_110k_results.bzcqp7rkcohort_first c1
join synpuf_110k_full.visit_occurrence vo1 on c1.subject_id = vo1.person_id
and vo1.visit_start_date >= DATE_ADD(IF(SAFE_CAST(c1.cohort_start_date  AS DATE) IS NULL,PARSE_DATE(‘%Y%m%d’, cast(c1.cohort_start_date  AS STRING)),SAFE_CAST(c1.cohort_start_date  AS DATE)), interval -365 DAY) and vo1.visit_start_date < c1.cohort_start_date
join synpuf_110k_full.cost cst1 on c1.subject_id = cst1.person_id
and cst1.person_id = vo1.person_id
and vo1.visit_occurrence_id = cst1.cost_event_id
where cost >= 0
and currency_concept_id in (44818668)
and cost_concept_id in (31978, 31973, 31980)
and visit_type_concept_id in (32025, 32028, 32022)
```

![image](https://user-images.githubusercontent.com/4144173/91877380-3526ef80-ec7e-11ea-8e61-3e3542da424c.png)

**Comment by chrisknoll** [comment]
The cost table should have a person_id on it (this has changed in recent CDM specs) have you checked if you have that in your env?

**Comment by konstjar** [comment]
@chrisknoll This issue was observed on v2.7.8 with OMOP CDM v5.3.1 that does not have person_id in [cost table](https://github.com/OHDSI/CommonDataModel/blob/v5.3.1/BigQuery/OMOP%20CDM%20bigquery%20ddl.txt#L562).  I believe if should be back compatible as most of datasets are on 5.x OMOP version still. What do you think?

**Comment by chrisknoll** [comment]
Strange,when we developed this code, we didn't have cdm v6 installed, but there was a person ID field, but you're right, thre is no person_id in 5.3.  In the environment we were developing this on (included Redshift, netezza and Pdw) the person ID was necessary in order to partition the distributed data (otherwise it gets replicated (which is very bad for a table that size) or random distribution (which makes queries slow if they need to be joined to other distributed tables).

But, CDM compatabiltiy is important, so it may be necessary to remove that column...but a question remains, given a record in the COST table, how do you determine which person owns the cost record?

**Comment by konstjar** [comment]
@chrisknoll It looks like I understand the reason. We had config.enableCosts set as true on ATLAS level. When you disable this feature, WebAPI does not run SQL code for cost table. In this case Full reports are generated properly. 
Thus, I'm closing the issue.
