### ISSUE TITLE
Database migrations are not applied in combination with disabled security

### ISSUE THREAD

**Issue by konstjar** [OHDSI/WebAPI#1658]
Master branch with 2.8. In case of disabled security, flyway does not populate clean database.

```
<security.provider>DisabledSecurity</security.provider>
```

Tested on SQL Server 12 and PostgreSQL 10.14 on Windows.

Log file attached
[tomcat8-stderr.2020-10-17.log](https://github.com/OHDSI/WebAPI/files/5396047/tomcat8-stderr.2020-10-17.log)

**Comment by chrisknoll** [comment]
I'm not seeing any reference to flyway in the logs...usually you see a 'Schema is up to date' or 'schema migrated to Version XXX.'.

The underlying issue was relation 'public.source' not found..is it possible there's a bean being activated before flyway had a chance to work?  It seems from the log this is in the stack trace:

```
at org.ohdsi.webapi.security.PermissionService.postConstruct(PermissionService.java:91)
``

Is it possible Permission Service is trying to do something that depends on the DB, but the DB hasn't been validated yet?
