### ISSUE TITLE
WebAPI 2.8.0 build error - .git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml

### ISSUE THREAD

**Issue by mintmountain89** [OHDSI/WebAPI#1733]
Hi there, 
We are having problems building the WebAPI.war file for release 2.8.0. The message that is that the git directory is not found in the pom.xml.

![image](https://user-images.githubusercontent.com/41219568/103749677-c3521e80-5040-11eb-98b0-896888adc794.png)

.git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml

Thanks!

**Comment by chrisknoll** [comment]
@wivern,  in this PR: https://github.com/OHDSI/WebAPI/pull/1453, you implemented the use of the git-commit-id-plugin.  However, I believe there's an issue when you get the sourcecode from the release (as a zip), you can't build the project because it can't get the .git information.  So, I think we need to skip the plugin if the project wasn't pulled from git.  I read that there is support for a 'skip' option, maybe we can by default skip but for dev, enable.   Or, maybe we need to externalize the git information from the build process, and commit a build info information to the repository as part of a release step?

I was looking through the documentation [here](https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/master/maven/docs/using-the-plugin.md), and it looks like we can make it so it doesn't fail when you don't have a git directory using this: `<failOnNoGitDirectory>true</failOnNoGitDirectory>`. Maybe that's an option? I don't know what happens if the plugin doesn't run and values aren't put into a property file (like the commit id).  

But if we want to capture some information about the build, even for stand-alone releases without a git repo, maybe we need to set a maven goal to output the file, and we execute this as a pre-release step. Not sure what the best way is for this. 

I'm definitely sure that we don't want to have a build error tho :)

**Comment by chrisknoll** [comment]
@mintmountain89 , in your local pom.xml file, could you try to make a local edit that may get around this error:

In the pom.xml, you have this content:

```
      <plugin>
        <groupId>pl.project13.maven</groupId>
        <artifactId>git-commit-id-plugin</artifactId>
        <version>4.0.0</version>
        <executions>
          <execution>
            <phase>validate</phase>
            <goals>
              <goal>revision</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <generateGitPropertiesFile>false</generateGitPropertiesFile>
        </configuration>
      </plugin>
```

Can you try modifying the `<configuration>` element:

```
<generateGitPropertiesFile>false</generateGitPropertiesFile>
<failOnNoGitDirectory>true</failOnNoGitDirectory>
```

Note: I think this will let the build pass, but it may leave null values in our application properties which may lead to NPE (null pointer exceptions) at run time, so this may not be a fix. Would you mind trying it out and letting us know?

**Comment by ParkChanghHyun** [comment]
Also you can solve this error by downloading "WebAPI" to 「git bash」.

It is  link about how to install 「git bash」
[](https://www.stanleyulili.com/git/how-to-install-git-bash-on-windows/)
 

And then you can follow this step.
1. Excute 「git bash」 and change your working directory in 「git bash」
2. Get URL to get git clone ( https://github.com/OHDSI/WebAP )
![image](https://user-images.githubusercontent.com/45930454/103987866-78ffa780-51d0-11eb-9a1f-83c1e10f1c74.png)

3.commend "git clone https://github.com/OHDSI/WebAPI.git" in 「git bash」
![image](https://user-images.githubusercontent.com/45930454/103988182-faefd080-51d0-11eb-835f-ce591ef27d74.png)


And then if you follow /OHDSI/WebAPI/wiki installation guide,
you can solve this problem.

**Comment by mintmountain89** [comment]
@chrisknoll Thanks, we tried to modify the pom.xml but it still failed to build

![image](https://user-images.githubusercontent.com/41219568/104022679-95650980-51fb-11eb-8d1a-e1a7c92edcaf.png)

attempted the git clone command suggested by @ParkChanghHyun , that worked and the build went through

**Comment by chrisknoll** [comment]
Ok, using the git clone is fine, just checkout to the release tag 2.8.0 using the command:
``` checkout v2.8.0 -- ``` 
otherwise you'll be using the latest master (which is fine if you want to test something, but not if you want to use the released version).

**Comment by mintmountain89** [comment]
Thanks, @chrisknoll
