### ISSUE TITLE
Allow users to prepare the database before starting the Web API

### ISSUE THREAD

**Issue by sdebruyn** [OHDSI/WebAPI#1793]
Any form of automated installation of the Web API is very difficult because you have to

1. Run WebAPI
2. Let it create the SQL tables
3. Manually insert records defining the CDM sources

To make it easier for people who embrace the devops way of working, it would be helpful to have a way to create these records before starting WebAPI for the first time or by providing the source and source_daimon records through configuration.

**Comment by chrisknoll** [comment]
So, we may be able to come up with a maven goal to deploy the database schema so that you can just do someting like:
`mvn flyway:deploy` 

After you do the first compile of WebAPI. That may launch the app just enough to deploy the schemas without starting up the entire HTTP endpoints and other services.   

I don't think we can automate inserting the CDM source records...but it's possible we could come up with some CLI that could take an input file (like JSON) and populate the source tables...and maybe all these steps could be wrapped up into a helper function.  

Any thoughts?

**Comment by sdebruyn** [comment]
hi @chrisknoll 

I was thinking about something similar, so your idea seems good to me!
At the moment I am working on an extension of the Broadsea Docker container that does the following:

1. Clone the repo with the same version as what the Broadsea container uses
2. Run flyway directly with the folder db/migrations
3. Use sqlcmd to insert the records in the daimon tables
4. Run the regular Broadsea startup

However, I'm not sure this will work correctly since I've noticed there are also some Java changesets and flyway wouldn't pick up on those if I'd run it this way. I hope that the missing changesets are applied as soon as the web API starts.

**Comment by chrisknoll** [comment]
Yes, there are sql and Java-based migrations, but I can't imagine that the devs of flyway didn't account for that for scanning a classpath in a war...ie: the classpath::// path to the resources/db folder should also support a way to scan packages under org.ohdsi.webapi...but I can ask the question on stack overflow and see if anyone has ideas.

**Comment by chrisknoll** [comment]
Ok, I found this documenation, but note: it was Version 7: 
https://flywaydb.org/documentation/concepts/migrations#java-based-migrations

There's a few options in there allowing you to add jar filess (maybe even WAR?) as a paramter, so that when you reference the locations with 'classpath:', it will have the jar on the classpath to scan.  It should just work, but this is for version 7 and I believe we are on V4.  I see that the latest supported versions of Flyway seem to be v6 and v7.  We may need to update the library to do what you want with the additional options, or just put an extra step that un-zipps the WAR into the class directory structure, and add params to find the unziped classes in the filesystem.  I'm sure there's a solution...

**Comment by chgl** [comment]
I faced the same issue when trying to Kubernetes-ify the OHDSI stack. I've written a custom script that is run as part of an init-Job when deploying the stack, see the comment here for the basic idea: https://github.com/OHDSI/Broadsea/issues/23#issuecomment-779378274

It waits for the WebAPI to have run its migrations and then inserts the connection details using psql (the postgres sqlcmd equivalent). This init-job automates the setup entirely, but requires a custom container that includes the CDM schema and vocabularies. It should work the same way in a docker-compose setup: start broadsea, DB, and the init-container at the same time, the latter is resilient enough to wait for both the webapi and DB to be available.

Making this configurable vs hard-coding a single source in a shell script as it is now should also work, though:

```yaml
cdmSources:
  - name: test cdm v5.3.1 
    key: test
    connection: jdbc:postgresql://..
    username: test
    password: ${TEST_CDM_SOURCE_PASSWORD}
  - name: synthea data
    key: syn
    connection: jdbc:mysql://..
    username: syn
    password: ${SYN_CDM_SOURCE_PASSWORD}
# ...
```

**Comment by chrisknoll** [comment]
I believe there's sufficient work-arounds or procedures available to get the desired result.  If there's a specific action, please comment here.
