### ISSUE TITLE
"This guide is not intended for setting up production systems"

### ISSUE THREAD

**Issue by artgoldberg** [OHDSI/WebAPI#1852]
The OHDSI WebAPI [installation guide](https://github.com/OHDSI/WebAPI/wiki/WebAPI-Installation-Guide) says "This guide is not intended for setting up production systems" and recommends that production systems run on Broadsea. But [Broadsea](https://github.com/OHDSI/Broadsea) is "In development" and has issued no releases.

What is the current recommended process for production deployments of the OHDSI WebAPI?

In particular, we're installing it on Linux, will use a Postgres dbms, and will access multiple CDMs running on SQL Server.

Thanks
Arthur

**Comment by chrisknoll** [comment]
The guide says 'not intended for production systems' because there are some short-cuts and simplifications that may not be considered appropriate for production level instances, ie default passwords or database permission settings. It's suggested that you apply the appropriate level of robustness to your own environment (which we don't know what level that is).

Broadsea is one implementation of a 'drop in' for installing the WebAPI/Atlas stack.  Most people just follow the instructions (pulling the repo, building the WAR, creating their databses, etc) but apply their own procedures and protocols related to configuring and securing the environment.

**Comment by artgoldberg** [comment]
Thanks for the quick clarification @chrisknoll .
