### ISSUE TITLE
Where can I find "achilles_result_concept_count" table DDL

### ISSUE THREAD

**Issue by ParkChanghHyun** [OHDSI/WebAPI#1882]
My Environment is
-WebAPI ver.2.80
-Oracle 12.2

### Expected behavior
SEARCH and show me the RC&DRC in Atlas .
![image](https://user-images.githubusercontent.com/45930454/118243399-5f9d9d80-b4d9-11eb-921f-f3401661015f.png)

### Actual behavior
It is TOO~~~~~much SLOW!
and 
this is show the ERROR
![image](https://user-images.githubusercontent.com/45930454/118243733-b86d3600-b4d9-11eb-841e-edbc1f589c2f.png)

### Steps to reproduce behavior

Where can I find "achilles_result_concept_count" table DDL?.

**Comment by chrisknoll** [comment]
It gets constructed when you run [Achilles](https://github.com/ohdsi/achilles).

**Comment by ParkChanghHyun** [comment]
Thanks, I done the Achilles and made "achilles_result_concept_count" table .
But still ATLAS "search" is too ~~ slow.
When I search "radiation" word, WebAPI 2.78 done just 30 second.
But It is more than 30min  in WebAPI 2.80.

I think it is need to  improve.

**Comment by chrisknoll** [comment]
yes, 30 minutes is way too long for a search query.

I'm not sure where the slowdown is for your environment:  is it the querying of the vocabulary tables or fetching the record counts from the database?  

Some things I would try:
- Restart WebAPI after the Achilles was run since I believe the caching of the record counts is performed only when WebAPI starts up
- Check your databsae configuration by running some of the vocabular queries.  YOu can find the vocabulary queries in the sourceccode, but it may be easier if you turn on logging on your MSSQL server and capture the queries that are running so slowly.  
- Setup SOLR: this will make the searching faster but the row counts are fetched in a separate query.  We haven't added setup instructions into the formal wiki, but the instructions can be found [here](https://github.com/OHDSI/WebAPI/pull/1091#issuecomment-565163067).

**Comment by ParkChanghHyun** [comment]
Thanks for your favor.
But it is still too slow.
I ran Achilles, so I have "achilles_result_concept_count" table .

In my Redshift Environment, some query run for 6 hour.
Look at this.


![image](https://user-images.githubusercontent.com/45930454/119422494-30d6c100-bd3c-11eb-99fa-0f75478102bf.png)
This query ocuurred, when I search "radiation" word in my Atlas.


=>After that's query end,  "radiation" word search is very fast.
But, when I search others words, it run that's query for a long time.

**Comment by anthonysena** [comment]
@ParkChanghHyun - just to add some additional ideas/thoughts to this thread: I'd recommend serving your vocabulary from a "traditional" RDMBS as opposed to RedShift. What we have found in our experience is that RedShift (and PDW) will queue queries based on the order in which they are received. Generally, vocabulary queries are fast but they can create a backlog of activity in the overall RedShift queue. Since I see you are using Oracle, you might want to consider a database/schema on that platform to host the vocabulary tables that you can use as your default vocabulary provider. The advantage here is that more intensive queries (i.e. cohort generation) will take advantage of the RedShift hardware without any additional interference from the vocabulary queries.

**Comment by ParkChanghHyun** [comment]
Thanks @anthonysena  !

Thanks to your TIPS, I changed my WepAPI setting like bellow.
So it's good working.
![image](https://user-images.githubusercontent.com/45930454/119790265-c0cc6480-bf0e-11eb-8447-bc56343198bd.png)

**Comment by ParkChanghHyun** [comment]
But I have problem in Hierarchy searching! 
I want to find Hierarch search, but it didnt act properly.
So how can I debug it's error.
In addition, this WEBAPI well working in only oracle setting. (Hierarchy search well work)

![image](https://user-images.githubusercontent.com/45930454/119791413-c5dde380-bf0f-11eb-8c4e-7964a3f93a22.png)

**Comment by chrisknoll** [comment]
The 403 response means authorization error.  Do you have security enabled?  if so, did you grant permissions to that datasource?

**Comment by ParkChanghHyun** [comment]
Thanks @chrisknoll.

Like your mentioned, it is well working on disabled security setting in Atlas.
But in enabled Atlas setting almost ATLAS function working well ,but only search concept Hierarchy function is didn't work.


**this is my solution.**
So I have two works for "Atlas  concept Hierarchy search" function.

1. insert "webapi.SEC_PERMISSION" table.
 ![image](https://user-images.githubusercontent.com/45930454/120138665-efe61d00-c211-11eb-96c4-62b74e031ea1.png)
2. insert "webapi.SEC_ROLE_PERMISSION" table.
![image](https://user-images.githubusercontent.com/45930454/120139168-df827200-c212-11eb-8897-cdbc419e3492.png)

And then it's working well.

**Comment by ParkChanghHyun** [comment]
I think it is becaues in Atlas some insert didn't work in Postgres.( In oracle ,I checked the well inserted "ancestorAndDescendant")
It should always insert manually? 
else, it is kind of error?
![image](https://user-images.githubusercontent.com/45930454/120140364-5f114080-c215-11eb-87e9-e3c199be84fb.png)


-my webAPI version is 2.80.
