### ISSUE TITLE
WebAPI not running after adding Authorization

### ISSUE THREAD

**Issue by gywlsdms123** [OHDSI/WebAPI#1947]
![image](https://user-images.githubusercontent.com/51704606/137697507-2dc2a570-0fa2-4740-a817-c73c66c0f2c3.png)

After logging in, errors occur in cohort generation, copying, and correction. and neither do concept set etc...
![image](https://user-images.githubusercontent.com/51704606/137698749-0ce0910a-ebf4-4319-b7c5-a5f63610f115.png)

And WebAPI doesn't work either.
Why is that?

![image](https://user-images.githubusercontent.com/51704606/137697926-b8556b7d-5a16-44ce-b8c3-3ddeea709bc5.png)
http://localhost:8080/WebAPI/info is working. 
But, 
![image](https://user-images.githubusercontent.com/51704606/137697981-7ef13b39-5bfc-43fc-b293-298d1c74f3ed.png)
http://localhost:8080/WebAPI/source/sources gives a 401 error.

I would appreciate it if you could send me a reply.

**Comment by alondhe** [comment]
the /info endpoint is valid, but there is nothing at / for webapi. And /source endpoint is not accessible just via browser once you add authentication. 

What errors are showing in the log when you do save study assets?

**Comment by anthonysena** [comment]
@gywlsdms123 - I'm going to close this due to age but if you are still having problems with this functionality, please re-open this issue. I'd suggest the following in your case: make sure you are using the most recent release of Atlas/WebAPI and make sure you restart WebAPI after making authentication changes just to rule out any stale information cached on the web server.
