### ISSUE TITLE
Consider adding the OpenTelemetry Java Agent for auto-instrumenting the service

### ISSUE THREAD

**Issue by chgl** [OHDSI/WebAPI#2066]
### Expected behavior

Distributed tracing is a great way to gain visibility into performance and operational characteristics of applications. Spring Boot supports distributed tracing via Spring Cloud Sleuth (https://spring.io/projects/spring-cloud-sleuth), but since the WebAPI is based on an older version of Spring Boot, it might not be compatible. An alternative way for Java services to add tracing without changing the source code is using a Java agent: https://github.com/open-telemetry/opentelemetry-java-instrumentation - this auto-instruments the app and traces WebAPI invocations, database interactions, and optionally exports metrics as well.

It would be helpful to add this Java instrumentation agent to the container image to opt-in to tracing support.

If this seems useful, I'd bee happy to create a PR to add this .jar to the container image. It will be similar to the one I previously created for the HAPI FHIR Server project over at https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/391/files. There's no real danger of any breaking changes since the agent has to be explicitly enabled and configured.

### Actual behavior

Currently, the WebAPI does not support any kind of tracing telemetry.

**Comment by leeevans** [comment]
@chgl I agree this would be a useful feature to add to the Docker container but I can also see that this may raise potential security concerns/questions if the Java agent is enabled in some production environments.

Can the Java agent be deployed so that it is completely disabled within the container image by default, with an explicit option (via environment variable?) to enable it to run only when tracing is needed? If it can be configured in that way then feel free to submit the PR request.

**Comment by chgl** [comment]
@leeevans thank you for the feedback! It's completely opt-in: while the agent jar resides in the container it is not used by the application by default. To enable it, the `JAVA_OPTS` env var has to be set to `-javaagent:/app/opentelemetry-javaagent.jar`. I'll create a PR soon.

**Comment by leeevans** [comment]
ok @chgl sounds good. Thanks.
