### ISSUE TITLE
ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by nzurawski** [OHDSI/WebAPI#2093]
### Expected behavior
WebAPI to load over SSL
### Actual behavior
WebAPI fails to load and developer tools console in Chrome shows an error that common name is invalid
### Steps to reproduce behavior
We have the WebAPI url in our config-local.js file for Atlas set as https://localhost:443/WebAPI/
I followed the Tomcat SSL configuration instructions using localhost as the common name

I have the settings.xml file for webapi setup to have ssl enabled and security set to AtlasRegularSecurity. The SSL Keystore file and password are defined as well. When loading Atlas though I unfortunately cannot get the WebAPI to respond and get the common name invalid error.

I've uploaded txt copies of the relevant files with sensitive information like passwords masked. Can anyone help me figure out what might be wrong here?
[server.txt](https://github.com/OHDSI/WebAPI/files/9687096/server.txt)
[config-local.txt](https://github.com/OHDSI/WebAPI/files/9687103/config-local.txt)
[settings.txt](https://github.com/OHDSI/WebAPI/files/9687110/settings.txt)

**Comment by anthonysena** [comment]
@nzurawski - just going to close this out since I believe we have addressed this through a private discussion. The summary I have here is that it is important to ensure that the SSL certificate is in good working order with WebAPI prior to configuring Atlas. If you have other details you'd like to share here, please do as it may help someone else who is facing this issue.
