### ISSUE TITLE
Null value in column "is_cache_enabled" of relation "source" violates not-null constraint due to missing default value

### ISSUE THREAD

**Issue by chgl** [OHDSI/WebAPI#2131]
### Expected behavior

Initializing the WebAPI `source` table [by following the Wiki](https://github.com/OHDSI/WebAPI/wiki/CDM-Configuration#source-and-source_daimon-table-setup) instructions or using existing SQL scripts that used to work in version 2.11 should also work in WebAPI 2.12.0.

### Actual behavior

https://github.com/OHDSI/WebAPI/pull/2077 added a boolean `is_cache_enabled` column which is not-null but doesn't specify a default value. This causes `INSERT`s that don't specify a value for `is_cache_enabled` to fail.

I believe this might be best mitigated by adding a new migration that sets the default value for `is_cache_enabled` to `true`, like so:

```sql
ALTER TABLE ${ohdsiSchema}.source ALTER COLUMN is_cache_enabled SET DEFAULT true;
```

Which should preserve the pre version 2.12 caching behavior.

I can take a stab at a PR if the suggestion makes sense!

### Steps to reproduce behavior

1. create an empty PostgreSQL database
2. launch the WebAPI
3. follow the Wiki instructions for setting up a source: https://github.com/OHDSI/WebAPI/wiki/CDM-Configuration#source-and-source_daimon-table-setup

**Comment by chrisknoll** [comment]
Hi,
 The wiki should be updated to indicate the new column, so that's a miss.  The question is that if it should be set to true or false by default.  In our environment we only have a select set of sources that we want to cache, so i'm not sure if we want to have it enabled by default or if we should disable by default and have them opt in.

**Comment by chgl** [comment]
I would also go for disabling it by default. The line 

https://github.com/OHDSI/WebAPI/blob/v2.12.0/src/main/resources/db/migration/postgresql/V2.12.0.202208110000__alter_source_cache_enable.sql#L2

already enables it by default for any *existing* sources when the migration runs so I'd say that's sufficient backwards compatibility. But any newly added sources have to either explicitly set their desired behavior or rely on the new default.

**Comment by chrisknoll** [comment]
That was a request by odysseus that they forced it to be enabled as part of 2.11 but this caused problems for us.   The compromise was that we'd migrate the existing sources as 'isCacheEnabled = true' for existing sources because that is how it worked in 2.11, but for new sources you add, we disable by default and have them opt in directly.

**Comment by chgl** [comment]
Gotcha! Should I create a PR with a migration setting the default value for the column to `false`.

**Comment by chrisknoll** [comment]
yeah, that sounds acceptable.
