### ISSUE TITLE
Moderator cannot manage tags from other users

### ISSUE THREAD

**Issue by mrechkem** [OHDSI/WebAPI#2161]
The "Moderator" role doesn't seem to have the permissions to update/assign tags besides those that owned or shared with the impacted users. Currently, only the Admin role allows tagging management of all assets via the "Tagging" module.  

This appears to be similar to the issue #2158, but pertaining to the management of reusables at the Moderator level.

**Comment by chrisknoll** [comment]
Asked on other thread, but didn't get a response there, so I'll ask here:

What is 'Moderator'? I think we have an understanding of 'admin', 'public' and 'atlas user', but Moderator?

**Comment by chrisknoll** [comment]
Thanks, it's strange that I've never heard of it, tho it was there in 2.7, it seems to have been unused or ... i'm not sure what to call it...'latent?' where the role for admin was present in the settings, but the role for Moderator was just added a few days ago.   I couldn't find anywhere in code that looked for that specific key in a security check, but I only did a search for it in code, not a deep search.

It seems like this sort of thing really should have some documentation backing it.  I checked the [security section](https://github.com/OHDSI/WebAPI/wiki/Atlas-Security), and nothing stand out there (they do talk about an administrator role, but don't say anything about a moderator role).  

I don't mean to make an issue about something that seems to have been there a while, but the issue is important to me because 1) I didn't know about it and I should have (not sure if that's my fault or a communication problem) 2) Introducing these pre-defined roles makes things more complicated (as we saw, we forgot about the Moderator role to do certain things, so we had a bug even in the v2.12 release), and what's to say that we don't come up with another  (or another 10) predefined roles (reviewer, consultant, support, etc etc).   My understanding was that role based security was flexible such that you could define any number of customized roles with permissions, so I would have expected that an 'exception' might be 'admin' but now I see that there could be any number of predefined roles with special semantics that aren't documented anywhere, and that just leads to more problems with support.

**Comment by chrisknoll** [comment]
Ok, so the solution sounds like that we should have granted some permissions into the moderator role related to tagging management, so I think we could accept a PR that grants those perms.  A short term work-around is just add the permissions to the moderator role directly in the UI, but I do understand that is an extra manual step.
