### ISSUE TITLE
Unable to GET path source/sources after enabling security

### ISSUE THREAD

**Issue by migldasilva** [OHDSI/WebAPI#2171]
### Expected behavior

Checking the contents of tables `SEC_PERMISSION` and `SEC_ROLE_PERMISSION`, it's expected to any user (public role) to GET the URL `source/sources` with no problem.

I have enabled security, and everything seems to be working. Users can login, permissions and roles are in place.

The idea is to use this URL in a healthcheck.

### Actual behavior

Calls to this URL returns 401 Unauthorized.

### Steps to reproduce behavior

Get Atlas working, and security enabled just like in:

https://github.com/OHDSI/WebAPI/wiki/Basic-Security-Configuration
https://github.com/OHDSI/WebAPI/wiki/Atlas-Security

**Comment by anthonysena** [comment]
Hi @migldasilva - are you trying to hit this endpoint `source/sources` by going to this endpoint in the browser? If so, this is likely why you are getting a 401 Unauthorized error since the authorization token that Atlas uses is sent as part of the HTTP header and just browsing outside of Atlas does not include this auth token in the header.

You might consider using the `WebAPI/info` endpoint for a health check since it allows for unauthenticated access.

**Comment by migldasilva** [comment]
r

**Comment by anthonysena** [comment]
Yes, `WebAPI/info` is intended to be accessible and should not require authentication. If this is failing, could you check your WebAPI's log and verify the service is running?

**Comment by alondhe** [comment]
Once you have your info endpoint available (meaning WebAPI is working fine), I would suggest using ROhdsiWebApi for seeing the source/sources endpoint. This package allows you to easily get the auth header via authorizeWebApi() and then can run getCdmSources().

**Comment by migldasilva** [comment]
@anthonysena Thanks for your answer. It took me a while to take this issue back. I can confirm that once authentication is enabled, the endpoint WebAPI/source/sources is no longer publicly available (authentication is required).

On the other hand, the endpoint WebAPI/info is publicly available indeed. As soon as I could test, this endpoint doesn't work if WebAPI is down. Thus, it could be used to check site availability.
