### ISSUE TITLE
Creating a schema using the Wiki does not appear to have the correct instructions.

### ISSUE THREAD

**Issue by Mack-254** [OHDSI/WebAPI#2206]
### Expected behavior
In PostgreSQL, a user can be granted various permissions on a schema using the "GRANT" command. Some of the commonly used schema-level permissions include:

USAGE: Allows a user to use objects within the schema, such as tables, views, and sequences.
CREATE: Allows a user to create new objects within the schema.
ALTER: Allows a user to modify existing objects within the schema.
DROP: Allows a user to remove objects from the schema.
SELECT, INSERT, UPDATE, DELETE: These permissions allow a user to perform the corresponding operations on tables within the schema.
To grant permissions on a schema to a user, the syntax is:
### Actual behavior
The instructions state:
To start, webapi_sa account requires the following permissions on these schemas:

schema	permissions
cdm	read-only
vocabulary	read-only
results	insert/delete/select/update
temp	full control (create/remove tables & data)

### Steps to reproduce behavior
The above permissions such as read-only do not exist on schemas.  Could you provide step by step instructions on setting up the cdm, results, temp and vocabulary  schemas to those who do not have a DBA to lean on.

**Comment by chrisknoll** [comment]
I think you are conflating the WebAPI database and schema set up with the CDM data source setup (that has cdm, results and temp schemas). 

For CDM configuration, the permissions of 'read-only' are recommended based on that the cdm data should not be written to (it's patient level data that you just query for analysis).  The results schema needs insert/delete/select/update permissions because that's where it writes results.  Temp schema needs full control because it will create/drop tables.

The [WebAPI PostgreSQL configuration](https://github.com/OHDSI/WebAPI/wiki/PostgreSQL-Installation-Guide) is to set up the WebAPI database.  The CDM configuration describes the schemas (cdm, results, temp) and the permissions that the user that you are connecting with (which is stored in the WebAPI's SOURCE table).
