### ISSUE TITLE
concept_hierarchy calls incorrect

### ISSUE THREAD

**Issue by jduke99** [OHDSI/WebAPI#268]
This appears multiple times in cdmresults api:

@results_database_schema.concept_hierarchy

It should be:

@vocabulary_database_schema.concept_hierarchy

**Comment by jduke99** [comment]
i think this was from update on October 10th (be4faa1855c06b32c5c0f5e6c654d43286b708bb)

Not sure if the correct syntax is @vocab_database_schema or @vocabulary_database_schema

**Comment by anthonysena** [comment]
Hi @jduke99 - the concept_hierarchy table is a new addition that is created as part of running Achilles v1.5 on your CDM. The idea is that the concept_hierarchy is constructed to pre-compute all of hierarchy relationships used by Achilles to improve performance when querying from WebAPI. So, we kept this table in the results schema since it is tied to the Achilles results.

This article on the wiki helps to explain the details for generating these new Achilles dependencies for WebAPI: http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:atlas:achilles_v_1_5

Let me know if you need anything else.

**Comment by chrisknoll** [comment]
Right, this table is in the results schema (it's not part of the standard CDM schema).

Closing this for now but please let us know if we need additional followup!
