### ISSUE TITLE
Sequences for entities

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#324]
@chrisknoll, @anthonysena, could you help me to understand, why WebAPI uses a single sequence (Hibernate's default sequence) for all entities, not a sequence per entity. So, rephrasing, why @SequenceGenerator annotation is not set and configured for all identifiers columns (e.g. to use database's `concept_set_sequence` for `ConceptSet` entity)? I guess, there was a good reason for it, so would be grateful for your clarification.

**Comment by pavgra** [comment]
Seems like the question was mentioned before - https://github.com/OHDSI/WebAPI/issues/187. So, @chrisknoll, would you mind, if we migrate all entities to their own sequences?

**Comment by anthonysena** [comment]
I'm supportive of making the change to having a sequence per table versus using the hibernate default sequence.

**Comment by chrisknoll** [comment]
I think all of the DBs we support for WebAPI supports the notion of sequences, so I'd rather go that route (it saves a db udpate call when we go to a sequencer vs. updating a table because the DB optimizes this type of operation).  There is a challenge:

> The challenge is creating the DDL for these sequencers that are initialized based on a value from a select max (id) from EntityTable. I'm sure this is possible on MSSQL, but more challenging on oracle.

If we do a migration for this, we need to create the migration script (one for each platform, mssql, oracle, postgresql) that can figure out the current max id for each table, and initialize a sequence to the  max(id) of the table in question.  Then the autonumber columns (in mssql case) needs to be dropped and replaced with just a simple int field...and there's primary keys and foreign keys invovled to make ti trick.  This is all technically possible, just a challenging task.  In my mind, the hardest part is getting this to work over in oracle world: on mssql i could declare a variable as the max ID of a table, and then create a sequence initializing it to the variable.  On oracle, can you do that? no idea.

Other option is to completely reset the clock with WebAPI 3.0 with brand new sequencers, and provide a way to migrate data from WebAPI 2.x to WebAPI 3.0 as a separate utility (ie: a CLI tool that takes a webAPI 2.0 path, a webapi 3.0 path, and given the identier, it loads from one webapiand saves as new to the other webapi).  Making it CLI means we could do it in a batch operation.

**Comment by chrisknoll** [comment]
> So, rephrasing, why @sequencegenerator annotation is not set and configured for all identifiers columns (e.g. to use database's concept_set_sequence for ConceptSet entity)? 

@pavgra , to answer your question above:  this is an artifact of the earliest days of WebAPI (back from 2013).  It's no one's fault, but we didn't have the expertise in JPA that we do today (nor the JPA version that we have today), and this is the default implementation we were given and it worked, so we went with it (didn't want to create 'santa-barbara' by challenging it).  So, it does serve as a good example of where talking it over first would have been better over taking the first implementation that was delivered, but this is the legacy we live with now.

**Comment by gowthamrao** [comment]
@chrisknoll @pavgra @anthonysens is this being worked on as part of 2.4 release?

**Comment by anthonysena** [comment]
Hi @gowthamrao - yes, this work will be part of the 2.4 release. The work is completed, reviewed and in master now so I'm going to close out this issue. Thanks!
