### ISSUE TITLE
Introduction for a Web2.0 neophyte

### ISSUE THREAD

**Issue by msuchard** [OHDSI/WebAPI#34]
I want to take an active step in learning how the great tools OHDSI is producing work; WebAPI seems like a very productive place to start.  But I have no experience with the technology and am having trouble making heads-from-tails of the source code.

Might I please ask if someone has a moment to briefly walk me through some basics.  For example,
1. How does one generate documentation that lists all of the services (did I use the right term?) available, like /vocabulary/**, /evidence/**, etc. ?  I feel so dumb because I can't even find a text string "vocabulary" in the source files.
2. What do the annotations do?  A short intro to Spring Boot didn't cover many that I see.
3. How do I get it running on my friendly MacBook to try things out?  `mvn clean install` generates pages and pages of errors.

Help ... I'm sinking.

**Comment by chrisknoll** [comment]
Hi,
  I'll do my best to answer:

Re: #1: i'm not sure how you are building the source, or if you are using an IDE.  The Java project is structured around a Maven build process. We did this so that we could let people use the IDE of their own choosing while maintaining project assets and dependencies in a IDE-independant way.  You can even kick off the build task from a command line that very much resembles npm or make.  We've added a maven plugin called 'miredot' which generates all the web-service documentation. If you have built the source, you should be able to find the documentation in /target/miredot in under the repo root.  I don't think anyone has generated javadocs for the code, and I, myself, have been extremely unprofessional about the amount of documentation I've added to my code, so sorry about that.  This should be something we should do considering the webAPI is relatively stable now.

Re 2: I'll answer this in 2 parts: general annotations and how the spring framework leverages them:

An annotation is used to apply some metadata to a class, field or function.  This metadata can be interrogated by the compiler: (such as the @override which you mark a method that you intend to override from a base class, and if the compiler finds no such overridden method, will warn you).  It can be interrogated at runtime: all the spring annotations are interrogated at runtime, but specifically classes that are marked as @Configuration at as pseduo-xml configuration classes that define what beans are available in the spring container.  What is a Spring container?  To much to explain here, but it takes some of the burden of object allocation out of the developer and puts it into the framework.  You can change an object from being a singleton to a session scoped object with a flick of a annotation value.  

 In Spring, Annotations are used mostly to remove any XML configuration work.  In the old days, every class that represented a component (known as a bean) had to be identified in a config file.  It was cool and all (you could replace a subsystem of beans with mocks for testing purposes without changing any actual code) but was extremely cumbersome to maintain:  you had to copy the class name into the xml file to config it. and if you rename the class? good luck finding it in the config files.  Now you can establish beans and dependencies between beans simply by annotating them, and the spring container interrogates the classes when it needs some information about a bean.

Another place annotations are used heavily in WebAPI is our Java Persistence framework.  This is the software that maps our Java classes into database rows and tables.  We just annotate a class as an '@entity' and declare which fields are @identity fields, and what the column names are that each fields mapps to with @column annotations, and the persistence framework does the work of writing the sql that reads and writes.  It will even leverage the database driver provider hints for optimizations.

Re 3: One thing about maven errors: they snowball. one little thing fail at the top will lead you to a mountain of errors as you get to the bottom.  We can help you work through the issues on the forum, if you can post a couple of the errors you see at the top of your log, and also give us some of the details about which IDE you are using (if any) and also some details about the Java runtime you are on.  I believe the maven pom.xml file is targeting java 1.7.

Hope that starts to help, i hate to see anyone drown!  I think the best way forward is to tackle one area of interest at a time because we puled in a HUGE techology stack into webAPI between Spring, Java Persistence architecture and other libraries that we depend on for JSON serialization, etc.  It's a lot of capability but also a lot of things to learn.

-Chris

**Comment by msuchard** [comment]
Hi Chris, thanks for stepping up!

I'm building from the command-line via maven:

```
fubini:WebAPI msuchard [master]$ mvn -version
Apache Maven 3.3.1 (cab6659f9874fa96462afef40fcf6bc033d58c1c; 2015-03-13T13:10:27-07:00)
Maven home: /usr/local/Cellar/maven/3.3.1/libexec
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.9.5", arch: "x86_64", family: "mac"
```

So, JDK 1.8 *should* (not sure) support 1.7.  Running `mvn clean install` generates:

```
2015-04-14 16:21:17.646 WARN main org.springframework.context.annotation.AnnotationConfigApplicationContext -  - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cohortImportExportService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: public org.ohdsi.webapi.cohortimportexport.CohortRepository org.ohdsi.webapi.cohortimportexport.CohortImportExportService.cohortRepository; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cohortRepository': Cannot create inner bean '(inner bean)#e27ba81' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#e27ba81': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/ohdsi/webapi/DataAccessConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.persistence.EntityManagerFactory]: Factory method 'entityManagerFactory' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'primaryDataSource' defined in class path resource [org/ohdsi/webapi/DataAccessConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'primaryDataSource' threw exception; nested exception is java.lang.IllegalStateException: Could not load JDBC driver class [com.microsoft.sqlserver.jdbc.SQLServerDriver]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
```

and then unfortunately `target/miredot` does not get made.  Hmmm, on second thought, that makes me a bit happier at least to know that document *will* get made.  Then, I can start tinkering.

**Comment by cahilton** [comment]
It looks like it's having problems creating the 'primaryDataSource'. Have you set the username/password/jdbc url, etc., either in the pom.xml or the external settings.xml? Also, depending on what database environment you're using, you may need to use a profile, so that your database jars are included (or you may have to manually have to include them in your build path). For example, at Regenstrief, we use mvn ... -P webapi-oracle.

**Comment by cahilton** [comment]
I guess the exciting news is we are getting pretty close on Olympus, which may help alleviate some of this pain. It's just not quite there yet.

**Comment by chrisknoll** [comment]
So thie exception:
nested exception is java.lang.IllegalStateException: Could not load JDBC driver class [com.microsoft.sqlserver.jdbc.SQLServerDriver]

Is key: are you using microsoft SQL server?  If so, there's an additional step you need to take in order to get the microsoft Jdbc driver registered in your local maven repository.

If you are using another database, let me know.  The instructions will be different if so.

-Chris

**Comment by msuchard** [comment]
Charity and Chris, many thanks!  

`mvn clean install -P webapi-postgresql` certainly gets me further along.  Now the tests fail when trying to contact 54.209.111.128:5432 which leads me to wanting to modify 

```
      <properties>
        <datasource.driverClassName>org.postgresql.Driver</datasource.driverClassName>
        <datasource.url>jdbc:postgresql://54.209.111.128:5432/vocabularyv5</datasource.url>
        <datasource.username>USER</datasource.username>
        <datasource.password>PASS</datasource.password>
        <datasource.dialect>postgresql</datasource.dialect>
        <datasource.cdm.schema>unrestricted</datasource.cdm.schema>
        <datasource.ohdsi.schema>ohdsi</datasource.ohdsi.schema>
        <datasource.cohort.schema>ohdsi</datasource.cohort.schema>
        <flyway.datasource.driverClassName>${datasource.driverClassName}</flyway.datasource.driverClassName>
        <flyway.datasource.url>${datasource.url}</flyway.datasource.url>
        <flyway.datasource.username>userWithWritesToOhdsiSchema</flyway.datasource.username>
        <flyway.datasource.password>PASS</flyway.datasource.password>
        <flyway.locations>classpath:db/migration/postgresql</flyway.locations>
      </properties>
```

from `pom.xml`.

* Is there a public readable `vocabularyv5` out there?  
* Do I need to host my own?  (not readily possible)

More importantly: how do I by-pass the tests and get straight to generating `target/miredot`?

**Comment by cahilton** [comment]
Try `mvn test -DskipTests=true` or `mvn install-DskipTests=true` (see http://www.miredot.com/docs/getting-started/)

Lee probably knows about the public one. I have the login info. for me, but IDK if there's a public username/password.

**Comment by alexfranken** [comment]
If it's the miredot documentation you are looking for, you can check out the continuous integration server. The following link should be the latest endpoint docs for the last commit to master.
http://webapidoc.ohdsi.org/job/WebAPI/ws/target/miredot/index.html
