### ISSUE TITLE
Data source reports, drill down issue in Atlas/WebAPI running on Redshift

### ISSUE THREAD

**Issue by leeevans** [OHDSI/WebAPI#340]
To reproduce this issue (on Redshift DBMS) Atlas/WebAPI 2.2.0:

In Atlas, on Redshift,  choose data sources, condition report and click on any condition in the heat map. No drill down charts are shown below the heat map. The same issue applies to other drill down reports.

I believe this is caused by the change "- update all drilldown reports sql files to cast stratum_x to INT rather than concept ID's to VARCHAR" that was part of issue #251 

The achilles_results_dist table stratum_1 contains a non-numeric entry (e.g. analysis_id 0 contains the data source name). Redshift essentially complains that it cannot cast a non-numeric value to an int. 

Whether or not this error is encountered may be dependent on the execution path taken by the DBMS SQL optimizer (ie. if it chooses to do the join prior to filtering by the analysis id in the where clause) which in turn can depend on the relative number of rows in the two tables, whether analyze was run etc.

Example SQL:
`
SELECT
  c1.concept_id,
  c2.concept_name   AS category,
  ard1.min_value,
  ard1.p10_value,
  ard1.p25_value,
  ard1.median_value,
  ard1.p75_value,
  ard1.p90_value,
  ard1.max_value
FROM ccae_results.ACHILLES_results_dist ard1
INNER JOIN
ccae.concept c1
ON CAST(ard1.stratum_1 AS INT) = c1.concept_id
INNER JOIN
ccae.concept c2
ON CAST(ard1.stratum_2 AS INT) = c2.concept_id
WHERE ard1.analysis_id = 406
AND c1.concept_id = 312648
`

Example error message:
`SQL state [XX000]; error code [500310]; [Amazon](500310) Invalid operation: Invalid digit, Value 'c', Pos 0, Type: Integer`

Additionally the web service call doesn't appear to return a 500 error when the SQL fails (it just has an empty json response "{}").

**Comment by pavgra** [comment]
Works in 2.4.3

**Comment by chrisknoll** [comment]
I could reproduce this issue on redshift, it has to do with how the records are returned, converted (via cast) and then filtered (via where clause / on clause).

Using the AWS tutorial environment, I was able to reproduce this, and, worse, i was unable to do any sort of table partitioning, indexing, or query sub-query group by (to try to force the optimizer to select only the desired records by analysis id) that would get the query to work.

There's a short term and a long term solution:

Short term:  switch the CASTs to cast the concept_id as varchar. This is much slower on MSSQL and probably postgresql too.

Long term:  make stratum_1 - stratum_5 into int or bigint, and within each analysis, set up a local 'stratum name' lookup that we can join to for the text value, but the data type isn't casted and then joined to an int column this way.  The longer term solution requires a bit more work to re-write the queries.

**Comment by pavgra** [comment]
@chrisknoll , hm, that's interesting. I've talked about Redshift here:

> Works in 2.4.3

Unfortunately, I cannot test latest master or 2.6.0 on Redshift: could you give me the failing SQL query?

**Comment by chrisknoll** [comment]
It's not the query, it's the data.  The query included would bring this up:

`SELECT c1.concept_id, c2.concept_name AS category, ard1.min_value, ard1.p10_value, ard1.p25_value, ard1.median_value, ard1.p75_value, ard1.p90_value, ard1.max_value FROM ccae_results.ACHILLES_results_dist ard1 INNER JOIN ccae.concept c1 ON CAST(ard1.stratum_1 AS INT) = c1.concept_id INNER JOIN ccae.concept c2 ON CAST(ard1.stratum_2 AS INT) = c2.concept_id WHERE ard1.analysis_id = 406 AND c1.concept_id = 312648
`

The issue is that casting ard1.stratum_1 as int blows up when there is some data in the table where stratum_1 is not numeric.   In the intial post:

> SQL state [XX000]; error code [500310]; [Amazon](500310) Invalid operation: Invalid digit, Value 'c', Pos 0, Type: Integer

It means that there was a row where stratum_1 was a word staring with 'c'.  

So, I do not have access to the tutorial enviornment, I may have recorded the specific query in that environment that failed, but the core of the issue is in MPP database systems, sometimes it will return all records, apply casting (which leads to the varchar-> int error) before applying the record filter.

I will try to locate the query.  I understand reproducing the error is important.
