### ISSUE TITLE
Fix feature extraction where censor period is being used

### ISSUE THREAD

**Issue by gklebanov** [OHDSI/WebAPI#364]
Fix feature extraction logic where censor period is being used

**Comment by pavgra** [comment]
## Problem description

Cohort w/ Features generation **without** Censor Window specified. Counts in generation table and features report are equal.
![2018-04-06 11_16_38-program manager](https://user-images.githubusercontent.com/10010071/38410488-5f336dae-398d-11e8-888a-1fbbed8afc26.png)

Cohort w/ Features generation **with** Censor Window specified. Counts in generation table and features report are **not** equal.
![2018-04-06 11_22_01-](https://user-images.githubusercontent.com/10010071/38410507-6d73571c-398d-11e8-9820-07dc18a42799.png)

**Comment by chrisknoll** [comment]
@pavgra , @gklebanov , @wivern,

One point of confusion here is that the report you're talking about is the 'inclusion report' not feature extraction.  Feature Extraction is based on the cohort start/end dates and is completely independent from the 'total' number you circled in the bottom half of your screenshot.

In your screenshot, the 'Total' column represents the total number of 'qualified events': ie the events that were selected from the 'initial events' after applying the 'initial event criteria'.  Note: this has nothing to do with censoring windows, because censoring windows are applied after matching all of the inclusion criteria, then collapsing those events into eras, and THEN we apply the censor window.  I'm having a hard time imagining how we can incorporate the censoring window into the inclusion rule report.  Also:  if you have a cohort definition that has 'use all events per person' you could have a situation where you have many more primary events in the inclusion report that gets collapsed into 1 record per person. This would make your screenshot above show the same sort of anomaly even without a censor window applied.


For the change made in OHDSI/circe-be#36: the proposed fix there is to only consider events inside the censoring window.  However, there are events that are outside the censor window that would allow a person to appear int he cohrot.  For example, consider a drug exposure:

```
Drug Exposure:    !------------!
Censor Window:      |----------------|
```

This Drug Exposure primary event would not be picked up even tho it did qualify the person into the cohort.  So, I feel the approach for applying censoring to the events for the inclusion rule report is flawed.  But, it is confusing to have those numbers labeled the same way, but they represent different things.  So I propose 2 things we could do:

1. Update the 'generate statistics' part of circe-be that it is a little more intuitive how to interpret the numbers.  I still don't know how to fold the inclusion rule counts into the censoring considering the censoring is applied after we collapse events into eras (such as the drug exposure example above). But maybe we can make it so that the inclusion rule report is more stand alone about inclusion rules and not censoring.  Maybe we need to add a place to store 'people lost from censoring'.

2. Change the labeling in the Atlas UI to be more explcit that the 'Total' in the inclusion report is talking about the number of primary events.
