### ISSUE TITLE
Ensure DDLs are encapsulated in "if not exists"

### ISSUE THREAD

**Issue by alondhe** [OHDSI/WebAPI#569]
In https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/ddl/results/concept_hierarchy.sql, we don't currently have an if clause around the command to only create the table if it doesn't exist. This is inconsistent with the other DDL scripts.

Can we make it a standard practice to use this conditional for any DDL?

**Comment by chrisknoll** [comment]
For flyway migrations, we don't want to do this because the flyway migration is the 'last word' on the table creation.  If a table already exists in the database but the migration script assumes it isn't, then the proper result is an error (a 'if not exists' would just skip the table, and there is no check if the table that already exists matches the expected definition).

Likewise, with the DDL scripts, if you blindly run the script, you should probably be aware that the DDL script attempted to create a table that already existed in the target database.  IN the case of the DDL web service, this isn't as critical because it is manually executed by a person, and they can figure out if the existing table is expected or not. 

So, we _might_ put in the 'if exists' checks for the DDL service, but not in 'any DDL' (which would include the flyway migration scripts).

**Comment by alondhe** [comment]
Fair enough. For CdmAtlasCutover, I'll just add in logic to check if the table exists before trying to run each results schema DDL.

**Comment by alondhe** [comment]
After trying the DDL service for our new post-processing package at Janssen, I noticed that the DDL service does encapsulate most table creates in an "if exists", however, a few still do not get that treatment. 

I'd like to be able to just hit the DDL service and have it run smoothly through all results tables.

**Comment by anthonysena** [comment]
Closed via #694 and related PRs.
