### ISSUE TITLE
Impala/Oracle cohort generation does not clean temporary tables in DB

### ISSUE THREAD

**Issue by konstjar** [OHDSI/WebAPI#576]
When cohort/IR generation is failed, temporary tables are not removed from CDM database. 
More of all I must not use CDM database/schema for creating temporary tables. Instead, we have to use Result schema.

![image](https://user-images.githubusercontent.com/4144173/45094573-62d70d80-b124-11e8-80c2-fdb69afdaaec.png)

**Comment by chrisknoll** [comment]
Oracle would suffer this same problem:  because there are no 'true' temp tables, we are forced to create real tables and then hope they clean up at the end.  

We had the notion of a 'temp schema' that could be used to store all temp table creations, i think the paramater to SqlRender was 'oracleTempSchema'.  This way, at least you have a schema that can store all of orphaned temp tablels and you can easily find them and remove them.
