### ISSUE TITLE
Cancel Cohort generation button doesn't kill underlying DB query

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#579]
### Steps to reproduce:
1. Start cohort generation
2. Press Cancel button
3. Execute (in case of PG):
```
SELECT pid, age(clock_timestamp(), query_start), usename, query 
FROM pg_stat_activity 
WHERE query != '<IDLE>' AND query NOT ILIKE '%pg_stat_activity%' 
ORDER BY query_start desc;
```

### Expected results
Cohort generation query is *not* presented in the results.

### Actual results
The query is presented in the results and still running.

**Comment by chrisknoll** [comment]
I was wondering how this worked when i saw the first implementation.

I think there's a limitation in JDBC drivers on how you can reliably cancel a running execution.  In apps like 'RStudio' if you try to cancel a action in a separate thread, you can click 'cancel' but nothing comes back from the UI until that thread is finished.

So, maybe the approahc for canceling jobs is that instead of making one huge batch-update statement that's sent across the wire, when you have a batch of statements, you execute them one-at-a-time, and between each invocation, you check to see if the job is cancelled. If the job is cancelled, you can close the job gracefully.

**Comment by chrisknoll** [comment]
Ok, if we can find a reliable way to cancel the executing statement, that would be idea.

Something to consider for a longer term problem:

On the platforms that do not support 'true' temporary tables (impala, oracle), we create permeannt tables with a random code prefix (aquazyer12_qualified_events, for example).  At the end of the query, if all is well, then those tables will get cleaned up.  However, if the query is interrupted, it leaves orphans.  Up to now, it was a problem only in cases where the execution was interrupted in an error (presumably rare events).  However, with a cancel button, we now have a 'normal, expected' case of queries terminating early. So, we might want to come up with a way on how to cleanup temp tables.
