### ISSUE TITLE
sqlProcedureTreemap.sql performance relatively poor

### ISSUE THREAD

**Issue by mav7014** [OHDSI/WebAPI#61]
In our environment the Heracles Viewer takes <6 seconds to generate the views we've tested to complete- with the exception of the procedures view which takes 9.9 **minutes**. We've isolated the bottleneck to be in [getProcedureTreemap](https://github.com/OHDSI/WebAPI/blob/master/src/main/java/org/ohdsi/webapi/service/CohortResultsService.java#L941) when executing the query [sqlProcedureTreemap.sql](https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/resources/cohortresults/sql/procedure/sqlProcedureTreemap.sql). We're currently attempting to use indexes to make the responsiveness of the procedures view more consistent with the others. Might there be a bug in the query? The OMOP instance in question is on SQL Server 2012.

**Comment by chrisknoll** [comment]
I think the performance problems cone when trying to determine the object hierarchy on the fly. It would be nice if there was a CDMv5 (or v6) enhancement to the vocabulary where there is a standardized hierarchy for purposes of categorizing the procedures/conditions/drugs for purposes of building these treemaps.

But right now, indexing on the vocab tables might help, but you could also look into 'indexed views', which is available in SQL2012, and effectively allows you to materialize a join (such as the ones specifeid in the procedure treemap query) so that the join is done against a cached, indexed virtual table.

**Comment by mav7014** [comment]
Thanks Chris- I'll pass this advice on to our DBAs

**Comment by mav7014** [comment]
It turns out we didn't have all the indices indicated by the [CDM DDL](https://github.com/OHDSI/CommonDataModel/blob/master/Sql%20Server/OMOP%20CDM%20indexes%20required%20-%20SQL%20Server.sql). Once they were added, performance improved significantly.

**Comment by cgreich** [comment]
Chris: What did you mean by "It would be nice if there was a CDMv5 (or v6) enhancement to the vocabulary where there is a standardized hierarchy for purposes of categorizing the procedures/conditions/drugs for purposes of building these treemaps."?

**Comment by chrisknoll** [comment]
In the Achilles queries, we do a rollup using a combination of concept_ancestor and the concept_class.  For drugs, it's using ATC levels, for procedures, it was using LOINC (which isn't really a good approach with cdm v5 vocab), and conditions?  Not exactly sure off the top of my head.

The point is, when we do a query to figure out which concept has which 'hierarchy' for the particular report, we have to derive this hierarchy (from concept_ancestor + concept_class plus other logic) on the fly and it's quite expensive.  Indexes help the problem, but seems wasteful to have to calculate the hierarchy on the fly for each analysis instead of just having a standardized reporting hierarchy table for each domain's concepts.  We could just load that up once and then use it over and over.  

-Chris
