### ISSUE TITLE
Export Cohort SQL filled with selected Source params

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#656]
Today Cohort Definition's Export tab allows to get translated, but not rendered SQL. So that placeholders for schemas still have to filled manually. Would be useful to be able to select a source of interest (e.g. with a dropdown in top-right corner above the SQL field) and receive fully cooked SQL ready for dropping into a database.

**Comment by gowthamrao** [comment]
@pavgra @chrisknoll 

I want to request additional functionality here. Would like the option for selecting the rendered SQL upto qualified events, and/or included events.

Example: I often times would like to use the ATLAS cohort build process, not just to get subjects that meet the cohort definition, but also to analyze the qualified events, or the included events.   See this cohort definition: http://www.ohdsi.org/web/atlas/#/cohortdefinition/1769505 ; I want the events that met the criteria of qualified events (visit_occurrence_id) and the included_events (visit_occurrence_id) - so that i may use these for further analysis - outside the cohort framework.

**Comment by anthonysena** [comment]
@schuemie has created a very nice Shiny app for doing this type of work:

http://data.ohdsi.org/SqlDeveloper/

I'd suggest using this for now since it should address the points made in this thread.

**Comment by anthonysena** [comment]
After consideration, I'm going to close this out. The SqlDeveloper app that is part of SqlRender meets our current needs and I think keeping that code in the SqlRender package makes sense at this point.

**Comment by pavgra** [comment]
> keeping that code in the SqlRender

But how implementation of the feature would grab any code from SqlRender? I would simply utilize the library in a very convenient way

**Comment by anthonysena** [comment]
My rationale for closing this issue was this: SqlDeveloper satisfies the needs describe in this issue, namely the ability to substitute values in the tokenized SQL and to translate the OHDSI-SQL to the target dialect. The service is hosted on OHDSI.org making it convenient for people that want to do this type of operation without having to start up their own Shiny service to do it. 

I'm not opposed to bringing this functionality into WebAPI but do not see this as an issue at this point that we need to address since there is a solution that exists. If you feel that this should be re-considered, please re-open the issue and we can discuss it further. Thanks!

**Comment by pavgra** [comment]
> substitute values in the tokenized SQL and to translate the OHDSI-SQL to the target dialect

That's the case - currently, you need to copy the cohort SQL, go to Configuration tab to figure out Source details (database schemas), copy the cohort id, paste these all into a website hosted on some separate domain and only then get the result.

If we implemented the feature, the only thing required for a user is to select a source of interest from the dropdown and copy fully cooked SQL.

**Comment by chrisknoll** [comment]
Sounds good.  The web service endpoint can accept a post of the options that will do the find replace, so the only missing piece is sending the right options to it.  Reading it from a source selection should work.

**Comment by anthonysena** [comment]
Closed via OHDSI/Atlas#2790
