### ISSUE TITLE
Heracles: The text data type cannot be selected as DISTINCT because it is not comparable.

### ISSUE THREAD

**Issue by mark-velez** [OHDSI/WebAPI#68]
We are using SQL Server 2012 and the Microsoft JDBC driver. Upon opening the Heracles runner UI, we encounter the exception "The text data type cannot be selected as DISTINCT because it is not comparable." I found out that the offending column was [heracles_visualization_data.data](https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/db/migration/sqlserver/V1.0.0.8__heracles_data.sql#L9). Changing the type from `text` to `varchar(max)` seems to solve the problem.

**Comment by mav7014** [comment]
@cahilton did you get a chance to review this issue? I think your assessment of this would be valuable.

**Comment by evillalonNY** [comment]
Yes, indeed heracles_visualization_data.data should be varchar(max) otherwise you get an error
SQL Error: 421, SQLState: S0001
2016-02-11 11:11:33.986 ERROR taskExecutor-1 org.hibernate.engine.jdbc.spi.SqlExceptionHelper -  - The text data type cannot be selected as DISTINCT because it is not comparable.

**Comment by cahilton** [comment]
That seems fine - I haven't had a chance to test with Oracle, but I can. Sorry, haven't been as active on OHDSI in the past few months.

**Comment by anthonysena** [comment]
Closed via #86
