### ISSUE TITLE
Feature Analyses update optimizations

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WebAPI#785]
Per @pavgra, we'd like to revisit #784 to get a better understanding of what is happening under the hood with the Hibernate session and transactions. The current implementation fixes the issue reported in #783 but is not the desired long-term solution.

**Comment by ssuvorov-fls** [comment]
The following happens:
1. FeAnalysisEntity savedEntity = findById (feAnalysisId) ...
Get the savedEntity object, which is attached to the persistence context. Objects in an array in the design field are also attached to the persistence context.
2. savedEntity.setDesign (updatedEntity.getDesign ())
We place in the design field an array from the updatedEntity object, which came to the server from the client and is not attached to the persistence context.
We get the situation when the parent object is attached to the persistence context, but the child objects do not.
3. userRepository.findByLogin (getCurrentUserLogin ())
When trying to get data from the database, the data associated with the persistence context and the database are synchronized, i.e. all objects marked as "dirty" are created or updated in the database.
The savedEntity object is attached to the persistence context, so the merge method is called for this object and for all fields of the object. But objects in the design array cannot be inserted or updated in the database, because not attached to persistence context. As a result, we get an error.

Possible solutions
1. Detach the savedEntity object from the persistence context by calling the detach function. 
2. Call the merge method for all objects in the array in the design field, which will attach these objects to the persistence context

**Comment by ssuvorov-fls** [comment]
Third solution - change cascade type to "MERGE" for children (design field) of FeAnalysisWithCriteriaEntity
