### ISSUE TITLE
FK_fac_sucid error during Flyway migration in SQL Server

### ISSUE THREAD

**Issue by NEONKID** [OHDSI/WebAPI#792]
When running WebAPI on SQL Server, the following error appears.

```
The object 'created_by_id' is dependent on column 'FK_fac_su_cid'
```
```
The object 'created_date is dependent on column 'DF___...'
```
```
The object 'modified_by_id' is dependent on column 'FK_fac_su_mid'
```
Dependent values that use foreign keys are fixed names, so clearing the constraint will resolve them, but 'create_date' is the default value and there is a variability in the name.

**Comment by YangDaeIl** [comment]
Oh, I have the same error. 
Did you happen to exclude additional modified_by_id; columns?

**Comment by anthonysena** [comment]
Sorry for this issue @NEONKID and @YangDaeIl - we are in the process of applying a fix for this issue here: https://github.com/OHDSI/WebAPI/pull/787.

As noted by @chrisknoll in that PR, once we merge this code into master, you'll need to rename the constraint on fe_analysis_criteria to DF_fe_analysis_criteria_cd (it will likely be something like DF__fe_analys_criter___....) in order for the amended flyway scripts to update your database properly.

**Comment by NEONKID** [comment]
@anthonysena Thanks. It seemed that the dependent value was DEFAULT and needed a defined name.
It seems to be the code resolved if the value dependent on this PR is DEFAULT. #793

**Comment by anthonysena** [comment]
That's exactly right @NEONKID - we made an attempt to revise the flyway script in #787 to provide a name for the default constraint in the hopes that people hadn't yet migrated to that point in master. I would agree that the approach that @wivern put together in #793 is a better approach and will allow us to handle the problem you and @YangDaeIl face. We'll work to merge that all together and put it into master very soon. Thanks!

**Comment by chrisknoll** [comment]
@NEONKID , we've merged various PRs into master to address this, would you mind pulling latest master and trying again? If your issue is resolved, go ahead and close this issue.
