### ISSUE TITLE
Broken older PostgreSQL support

### ISSUE THREAD

**Issue by jmbanda** [OHDSI/WebAPI#837]
The latest version of WebAPI uses instructions of the following type for migration:

ALTER TABLE table ADD IF NOT EXISTS 

This IF NOT EXISTS feature is from PostgreSQL 9.6 and on, breaking support for anything before that version.

**Comment by chrisknoll** [comment]
From a migration perspective, we should not need to use `IF NOT EXISTS` because the migration should know exactly what the prior state was and what the future state should be.  The `IF NOT EXISTS` means you may not know exactly what is the current state, which is not an assumption that we should make with migrations.

If something already exists where we expect it not to exist, the migration should fail.

**Comment by anthonysena** [comment]
Related to #676.

**Comment by anthonysena** [comment]
Fixed via #1486.
