### ISSUE TITLE
NPE in GenerateCohortTasklet

### ISSUE THREAD

**Issue by cataphract** [OHDSI/WebAPI#89]
I tried to generate a cohort through CIRCE and the Spring Batch job threw a NPE in GenerateCohortTasklet.java:120. I fixed in [this commit](https://github.com/thehyve/WebAPI/commit/d40346661f7819312bf74d309cc25f5a67b57cc5).

I wonder, though, if I'm doing something wrong, like using an unstable code base. I used the master branch from webapi. The commit that introduced the comparison of `Integer`s with `==` is already pretty old (https://github.com/OHDSI/WebAPI/commit/ea1e671921daeb7abe47a2d384794ea0ba0c7cd9 ), and what I was doing doesn't seem marginal functionality.

**Comment by chrisknoll** [comment]
Hi, @cataphract , Good find, but we've been doing that sort of comparison for a long time, and it hasn't been an issue, probably because the SourceID is coming from the same Integer instances.  But, the suggestion of using .equals() is a good one because we really want to compare values, not references.

if You'd like to make a Pull request on that file change, that's fine, just pull latest from webapi and make a PR off of the latest master.  It looks like the only change is to use .equals() to find the correct Source.

**Comment by chrisknoll** [comment]
@cataphract I'm thinking I can just push this into master, so disregard, I'll update.

**Comment by chrisknoll** [comment]
Fixed. Put wrong commit message, unfortunately :(  But this is updated in master.
