### ISSUE TITLE
migration #718 added conflicting pk

### ISSUE THREAD

**Issue by limadm** [OHDSI/WebAPI#893]
Hi,
`V2.6.0.20181128150100__add_missing_pk.sql` in #718 added some primary keys, such as `ALTER TABLE ${ohdsiSchema}.cohort_inclusion ADD PRIMARY KEY (cohort_definition_id);`.

After the update, starting WebAPI gives `PSQLException: ERROR: could not create unique index "cohort_inclusion_pkey"` because my `cohort_inclusion` table is something like:
```
cohort_definition_id | rule_sequence | name        | description
                   2 |             0 | middle-aged | [NULL]
                   2 |             1 | male        | [NULL]
                   3 |             0 | Dx          | [NULL]
                   3 |             1 | 18+         | [NULL]
                   3 |             2 | M/F         | [NULL]
```
To me it seems that `(cohort_definition_id, rule_sequence)` should be the primary key of cohort_inclusion, as that migration does not work on a populated database.

**Comment by chrisknoll** [comment]
You are absolutely right, that table should never had a PK assigned to it.   The origional issue was talking about cohort characterization tables PK, and that was pushed over to these tables.

@pavgra, @aklochkova , in this case, what we may want to do is alter this migration script to remove the PK on cohort_inclusion, and in a seperate migration remove the PK if it exists, or alternatively, put something in release notes to tell people to drop the PK on this table.  I don't like conditionals in our migration scripts, as you know, but in this case, for people that have data in their tables, this migration will fail, and for those who don't they will succeed....and hence for 2.7, we don't know if we need to clean up the PK or not.

**Comment by chrisknoll** [comment]
@limadm , when reviewing this further, it looks like you are using the 'example tables' that are installed into the webAPI schema instead of using the DDL service (/WebAPI/ddl/results) to create the results schema.

The example tables (that I describe here:  https://github.com/OHDSI/WebAPI/pull/902) where never intended to be used as the results schema, and when the devs attempted to create PK constraints on these tables, it introduced problems for people that were writing results to the webAPI schema.

So, the #902 pr is going to try to undo all the problems here, but for your environment, I **strongly** suggest you separate your CDM results schema from your WebAPI schema by setting up a different database instance, and in that separate database instance, you store your CDM/Vocabulary/Results tables.  In a future release of WebAPI we will be _automatically_ dropping those example tables so we do now want to see anything break in your environment, so please migrate those tables out of WebAPI.

**Comment by chrisknoll** [comment]
@leeevans : I think this impacts you as well, since I think I recall you stated that you are using the WebAPI's example tables for the results schema in on of your database instances on ohdsi.org (I think it was the origional synpuff?) If so, please migrate those tables from WebAPI schema out to a dedicated Results Schema and be prepared for a future release to **drop** the tables from the WebAPI schema.

Thanks!

**Comment by chrisknoll** [comment]
@limadm , as discussed in #902, we don't want to re-write our prior migrations to fix your issue. Instead, I'd like to guide you to migrating your tables from your WebAPI schema out into a separate schema that is co-located on the same database as your CDM. I am guessing that your environment has 1 database with your CDM and WebAPI schemas on it.  This is fine, but you should also have a separate Results schema that contains all the appropriate results tables installed in it.  Here's what you need to do:

Steps:
1. Create a results schema (give it whatever name but i will call it 'results' here).

2. From your WebAPI schema, copy the following tables into the new results schema:

cohort | heracles_analysis
COHORT_FEATURES | feas_study_result
COHORT_FEATURES_DIST | feas_study_index_stats
COHORT_FEATURES_REF | heracles_heel_results
COHORT_FEATURES_ANALYSIS_REF | heracles_results
cohort_inclusion | heracles_results_dist
cohort_inclusion_result | ir_analysis_dist
cohort_inclusion_stats | ir_analysis_strata_stats
cohort_summary_stats | ir_analysis_result
feas_study_inclusion_stats | ir_strata

3. After copy is complete, TRUNCATE all those tables in your WebAPI schema that are in the above list.

4. Launch WebAPI. Your failed migration should now succeed because there will not be any data to conflict with the PK creation.

5. Go to /WebAPI/ddl/results and get the entire results schema DDL, and check that all tables you need are created in your results schema.  The talbes that you truncated in WebAPI are only a subset of the full results schema, and you will need to review each table creation in the /ddl/results endpoint to ensure you have it created in your results schema.


That should resolve your problem. I'm very sorry for the issues you had and for making you migrate your tables to the proper results schema structure, but this is better in the long term.

**Comment by limadm** [comment]
@chrisknoll Thank you very much for the clarification, and please do not feel worried as I keep a separate local environment to test updates before pushing to our server. :smile:
