### ISSUE TITLE
Gradient Boosting Machine Error in PLP Package Creation

### ISSUE THREAD

**Issue by jswerdel** [OHDSI/WebAPI#976]
After selecting GBM as the machine algorithm, the package gets an error on execution:
> execute(connectionDetails = connectionDetails,
+         cdmDatabaseSchema = cdmDatabaseSchema,
+         cohortDatabaseSchema = cohortDatabaseSchema,
+         cohortTable = cohortTable,
+         outputFolder = outputFolder,
+         createProtocol = T,
+         createCohorts = T,
+         runAnalyses = T,
+         createResultsDoc = T,
+         packageResults = T,
+         createValidationPackage = T,
+         minCellCount = 5)
Error in (function (ntrees = c(10, 100), nthread = 20, maxDepth = c(4,  : 
  unused arguments (nThread = 20, nTrees = NULL)

**Comment by anthonysena** [comment]
2 issues here:

1. The case of the properties in the GradientBoostingMachine are incorrect - they should be "nthreads" and "ntrees" vs "nThreads" and "nTrees". This requires an update to the StandardizedAnalysisApi.
2. The ntrees setting in not properly exported due to this mismatch in case since Atlas was properly using the lowercase version of this property.
